<script lang="ts">
import { defineComponent, inject } from 'vue';
import { Refresh } from '@element-plus/icons-vue';
import { feishuWorkbenchContextKey } from '../dashboard-context';

export default defineComponent({
  name: 'FeishuWorkbenchView',
  setup() {
    const dashboard = inject(feishuWorkbenchContextKey);
    if (!dashboard) throw new Error('Feishu workbench requires the dashboard shell context');
    return { ...dashboard, Refresh };
  },
});
</script>

<template>
  <el-alert v-if="feishuWorkbenchError" :title="feishuWorkbenchError" type="error" show-icon :closable="false" class="section-gap"/>
  <el-card shadow="never" class="group-relay-status-panel">
	            <template #header><div class="card-header"><div><span>飞书分析师工作台</span><small class="realtime-refresh-time">与群监听状态同时每 10 秒刷新；前端操作只作用于机器人发送的汇总消息，行动卡片为可选增强。</small></div><el-space><el-button size="small" :loading="feishuWorkbenchAction === 'application-inspection'" @click="inspectFeishuApplication">复核后台配置</el-button><el-button size="small" :icon="Refresh" :loading="feishuWorkbenchLoading" @click="loadFeishuWorkbench">刷新</el-button></el-space></div></template>
	            <el-descriptions :column="mobileLayout ? 1 : 5" border size="small"><el-descriptions-item label="汇总群"><el-tag :type="feishuWorkbench.target_configured ? 'success' : 'danger'">{{ feishuWorkbench.target_configured ? '已配置' : '未配置' }}</el-tag><div v-if="feishuWorkbench.application_inspection" class="workbench-source"><el-tag size="small" :type="targetChatInspectionTagType(feishuWorkbench.application_inspection)">{{ targetChatInspectionLabel(feishuWorkbench.application_inspection) }}</el-tag></div></el-descriptions-item><el-descriptions-item label="用户读取授权"><el-tag :type="feishuWorkbench.user_oauth_configured ? oauthAuditTagType(feishuWorkbench.user_oauth_scope_audit) : 'danger'">{{ feishuWorkbench.user_oauth_configured ? oauthAuditLabel(feishuWorkbench.user_oauth_scope_audit) : '未配置' }}</el-tag></el-descriptions-item><el-descriptions-item label="缺失用户权限"><span v-if="feishuWorkbench.user_oauth_scope_audit?.verified === false">{{ feishuWorkbench.user_oauth_scope_audit.missing_scopes?.join('、') }}</span><span v-else>无</span></el-descriptions-item><el-descriptions-item label="后台配置复核"><el-tag :type="applicationInspectionTagType(feishuWorkbench.application_inspection)">{{ applicationInspectionLabel(feishuWorkbench.application_inspection) }}</el-tag></el-descriptions-item><el-descriptions-item label="H5 工作台"><el-link v-if="feishuWorkbench.public_h5_url" :href="feishuWorkbench.public_h5_url" target="_blank" type="primary">打开 H5</el-link><span v-else>待配置公网 HTTPS 地址</span></el-descriptions-item></el-descriptions>
	            <el-alert v-if="feishuWorkbench.application_inspection?.message" :title="feishuWorkbench.application_inspection.message" :type="feishuWorkbench.application_inspection.status === 'verified' ? 'success' : feishuWorkbench.application_inspection.status === 'not_checked' ? 'info' : 'warning'" :closable="false" class="section-gap"/>
	            <el-divider content-position="left">飞书事件与回调验收</el-divider><el-alert title="“等待首个回调”表示本地处理器已注册，但尚不能证明开发者后台已订阅该事件；在飞书内完成一次对应动作后会显示最近回调时间。" type="info" :closable="false" class="section-gap"/><el-table :data="feishuWorkbench.event_subscriptions ?? []" size="small" max-height="210"><el-table-column prop="label" label="本地处理器" min-width="140"/><el-table-column prop="event_type" label="飞书事件" min-width="225"/><el-table-column prop="required_for" label="用途" min-width="145"/><el-table-column label="验收状态" width="125"><template #default="{ row }"><el-tag size="small" :type="row.state === 'received' ? 'success' : 'warning'">{{ row.state === 'received' ? '已收到回调' : '等待首个回调' }}</el-tag></template></el-table-column><el-table-column label="最后回调" min-width="155"><template #default="{ row }">{{ dateText(row.last_received_at) }}</template></el-table-column></el-table>
  </el-card>
	            <el-row :gutter="14"><el-col :xs="24" :lg="14"><el-card shadow="never" header="最近汇总消息 · 协作状态"><el-empty v-if="!feishuWorkbenchMessages.length" description="暂无群消息记录"/><el-table v-else :data="feishuWorkbenchMessages" size="small" max-height="560"><el-table-column label="来源" min-width="120"><template #default="{ row }"><el-tag size="small" effect="plain">#{{ row.route_tag }}</el-tag><div class="workbench-source">{{ row.source_chat_name || row.source_key }}</div></template></el-table-column><el-table-column label="内容" min-width="220" show-overflow-tooltip><template #default="{ row }">{{ workbenchMessageText(row) }}</template></el-table-column><el-table-column label="状态" width="112"><template #default="{ row }"><el-tag size="small" :type="row.workflow_state === 'focus' ? 'warning' : row.workflow_state === 'ignored' || row.source_deleted ? 'info' : 'success'">{{ workbenchWorkflowText(row.workflow_state) }}</el-tag></template></el-table-column><el-table-column label="更新时间" min-width="145"><template #default="{ row }">{{ dateText(row.updated_at) }}</template></el-table-column><el-table-column label="协作" width="260" fixed="right"><template #default="{ row }"><el-button link type="primary" :loading="feishuWorkbenchAction === `${row.source_message_id}:research`" @click="runWorkbenchAction(row, 'research')">研究</el-button><el-button link type="warning" :loading="feishuWorkbenchAction === `${row.source_message_id}:focus`" @click="runWorkbenchAction(row, 'focus')">关注</el-button><el-button link :loading="feishuWorkbenchAction === `${row.source_message_id}:task`" @click="runWorkbenchAction(row, 'task')">任务</el-button><el-button link type="info" :loading="feishuWorkbenchAction === `${row.source_message_id}:ignore`" @click="runWorkbenchAction(row, 'ignore')">忽略</el-button><el-dropdown trigger="click"><el-button link>更多</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item @click="runWorkbenchAction(row, 'pin')">置顶汇总消息</el-dropdown-item><el-dropdown-item @click="runWorkbenchAction(row, 'urgent')">发送加急提醒</el-dropdown-item><el-dropdown-item divided @click="runWorkbenchAction(row, 'translate')">翻译</el-dropdown-item><el-dropdown-item @click="runWorkbenchAction(row, 'ocr')">图片 OCR</el-dropdown-item><el-dropdown-item @click="runWorkbenchAction(row, 'transcribe')">音频转写</el-dropdown-item><el-dropdown-item divided @click="runWorkbenchAction(row, 'archive')">沉淀到文档/Wiki</el-dropdown-item></el-dropdown-menu></template></el-dropdown></template></el-table-column></el-table></el-card></el-col>
	            <el-col :xs="24" :lg="10"><el-card shadow="never" header="消息检索（用户权限）"><el-input v-model="workbenchSearch" placeholder="搜索可访问的飞书消息" clearable @keyup.enter="searchFeishuMessages"><template #append><el-button :loading="feishuWorkbenchAction === 'search'" @click="searchFeishuMessages">搜索</el-button></template></el-input><el-alert title="搜索不会把结果自动转发；仅用已保存的用户 OAuth 权限执行。" type="info" :closable="false" class="section-gap"/><el-divider content-position="left">内容沉淀与协作</el-divider><el-space wrap><el-button size="small" @click="openWorkbenchIntegration('documents')">新建文档</el-button><el-button size="small" @click="openWorkbenchIntegration('wiki-documents')">归档到 Wiki</el-button><el-button size="small" @click="openWorkbenchIntegration('base-records')">写入 Base</el-button><el-button size="small" @click="openWorkbenchIntegration('calendar-events')">创建提醒</el-button><el-button size="small" @click="openWorkbenchIntegration('approvals')">发起审批</el-button><el-button size="small" type="primary" :loading="feishuWorkbenchAction === 'digest'" @click="createWorkbenchDigest">生成摘要</el-button><el-button size="small" :loading="feishuWorkbenchAction === 'group-tab'" @click="createWorkbenchTab">创建群 Tab</el-button></el-space><pre v-if="workbenchSearchResult" class="workbench-result">{{ JSON.stringify(workbenchSearchResult, null, 2) }}</pre></el-card></el-col></el-row>
	          <el-card shadow="never" header="已挖掘能力与接入状态"><el-alert title="“已接入”只证明服务端与前端入口存在；“权限验收”才反映已保存的用户 OAuth 范围或仍需飞书后台发布。应用身份权限和资源可见性需在首次真实调用后由飞书确认。" type="info" :closable="false" class="section-gap"/><el-table :data="feishuWorkbench.capabilities ?? []" size="small" max-height="540"><el-table-column prop="category" label="分类" width="105"/><el-table-column prop="label" label="能力" min-width="175"/><el-table-column label="实现" width="100"><template #default="{ row }"><el-tag size="small" :type="row.implementation_ready !== false ? 'success' : 'info'">{{ row.implementation_ready !== false ? '已接入' : '未接入' }}</el-tag></template></el-table-column><el-table-column label="资源" width="105"><template #default="{ row }"><el-tag size="small" :type="(row.resource_configured ?? row.configured) ? 'success' : 'warning'">{{ (row.resource_configured ?? row.configured) ? '已配置' : '待配置' }}</el-tag></template></el-table-column><el-table-column label="权限验收" min-width="140"><template #default="{ row }"><el-tag size="small" :type="capabilityAuthorizationTagType(row)">{{ capabilityAuthorizationLabel(row) }}</el-tag><div v-if="row.missing_user_scopes?.length" class="workbench-source">{{ row.missing_user_scopes.join('、') }}</div><div v-if="row.missing_tenant_scopes?.length" class="workbench-source">{{ row.missing_tenant_scopes.join('、') }}</div></template></el-table-column><el-table-column label="所需权限/产品" min-width="220"><template #default="{ row }"><el-tag v-for="scope in row.requires" :key="scope" size="small" effect="plain" class="workbench-scope">{{ scope }}</el-tag></template></el-table-column><el-table-column prop="note" label="边界与下一步" min-width="300" show-overflow-tooltip/></el-table></el-card>
</template>
