<script lang="ts">
import { defineComponent, inject } from 'vue';
import { Refresh, WarningFilled } from '@element-plus/icons-vue';
import VChart from 'vue-echarts';
import { dashboardContextKey } from '../../dashboard-context';
import TenDayLeaderRotationPanel from '../../components/TenDayLeaderRotationPanel.vue';

type BoardItem = { sector_key: string };

export default defineComponent({
  name: 'CloseReviewTab',
  components: { Refresh, VChart, WarningFilled, TenDayLeaderRotationPanel },
  setup() {
    const dashboard = inject(dashboardContextKey);
    if (!dashboard) throw new Error('research tab requires the dashboard shell context');
    return dashboard as Record<string, any>;
  },
});
</script>

<template>

  <el-alert title="复盘页只读取已保存的板块报告、市场快照和龙虎榜。龙虎榜是收盘后公开的次日观察背景，不参与当天盘中评分。" type="info" :closable="false" show-icon/>
  <el-row :gutter="14" class="section-gap">
    <el-col :md="4" :xs="12"><el-card shadow="never" class="metric-card"><span>市场状态</span><strong class="review-metric">{{ closeStrategyReview?.market_state ?? '待生成' }}</strong></el-card></el-col>
    <el-col :md="4" :xs="12"><el-card shadow="never" class="metric-card"><span>多指数状态</span><strong class="review-metric"><el-tag :type="indexRegimeType">{{ indexRegimeLabel }}</el-tag></strong></el-card></el-col>
    <el-col :md="4" :xs="12"><el-card shadow="never" class="metric-card"><span>区间中位修复</span><strong>{{ closeIndexRegime?.median_range_retracement === undefined ? '-' : outcomePercent(closeIndexRegime.median_range_retracement) }}</strong></el-card></el-col>
    <el-col :md="4" :xs="12"><el-card shadow="never" class="metric-card"><span>概念成员覆盖</span><strong>{{ conceptBackfill.mapped_concepts }} / {{ conceptBackfill.total_concepts }}</strong></el-card></el-col>
    <el-col :md="4" :xs="12"><el-card shadow="never" class="metric-card"><span>本次回填完成</span><strong>{{ completedBackfillBoards }}</strong></el-card></el-col>
    <el-col :md="4" :xs="12"><el-card shadow="never" class="metric-card"><span>板块报告时间</span><strong class="review-metric">{{ closeBoardReport ? dateText(closeBoardReport.observed_at) : '待保存' }}</strong></el-card></el-col>
  </el-row>
  <el-card shadow="never" class="section-gap">
    <template #header><div class="card-header"><div><span>短线交易七步复盘</span><small class="realtime-refresh-time">情绪 → 连板梯队 → 板块结构 → 资金/龙虎榜 → 亏钱效应 → 风向标 → 次日预案；只读取收盘前已保存证据。</small></div><el-tag :type="closeShortTermReview?.status === 'completed' ? 'success' : 'warning'">{{ closeShortTermReview?.methodology ?? '待生成' }}</el-tag></div></template>
    <el-alert v-if="!closeShortTermReview" title="尚未生成七步复盘；请先保存收盘板块复盘。" type="warning" :closable="false" show-icon/>
    <template v-else>
      <el-row :gutter="12">
        <el-col :md="4" :xs="12"><el-statistic title="短线情绪" :value="closeShortTermReview.market_emotion?.state ?? '-'"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="涨停 / 跌停" :value="`${closeShortTermReview.market_emotion?.limit_up_count ?? 0} / ${closeShortTermReview.market_emotion?.limit_down_count ?? 0}`"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="昨日涨停溢价" :value="closeShortTermReview.market_emotion?.previous_limit_average_change_pct ?? 0" suffix="%" :precision="2"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="最高连板" :value="closeShortTermReview.ladder?.highest_board_count ?? 0" suffix="板"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="成交额前20上涨" :value="closeShortTermReview.capital_and_lhb?.top_amount_advancers ?? 0"/><el-text size="small" :type="closeShortTermReview.capital_and_lhb?.top_amount_evidence_status === 'completed' ? 'success' : 'warning'">日线样本 {{ closeShortTermReview.capital_and_lhb?.daily_symbol_count ?? 0 }}</el-text></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="成交额前20下跌" :value="closeShortTermReview.capital_and_lhb?.top_amount_decliners ?? 0"/><el-text size="small" :type="closeShortTermReview.capital_and_lhb?.top_amount_evidence_status === 'completed' ? 'success' : 'warning'">{{ closeShortTermReview.capital_and_lhb?.top_amount_evidence_status === 'completed' ? '全市场可解释' : `局部/异常样本：${(closeShortTermReview.capital_and_lhb?.top_amount_quality_flags ?? []).join(', ') || '勿解读集中度'}` }}</el-text></el-col>
      </el-row>
      <el-alert class="section-gap" :title="closeShortTermReview.market_emotion?.interpretation ?? '情绪证据不足'" :type="closeShortTermReview.market_emotion?.state === 'risk_on' ? 'success' : closeShortTermReview.market_emotion?.state === 'risk_off' ? 'warning' : 'info'" :closable="false" show-icon/>
      <el-row :gutter="14" class="section-gap">
        <el-col :md="8" :xs="24"><el-card shadow="never" header="连板梯队"><el-space wrap><el-tag v-for="gap in closeShortTermReview.ladder?.gaps_below_highest ?? []" :key="gap" type="warning">缺 {{ gap }} 板</el-tag><el-tag v-if="!(closeShortTermReview.ladder?.gaps_below_highest?.length)" type="success">无明显断层</el-tag><el-tag type="info">二板及以上 {{ closeShortTermReview.ladder?.multi_board_count ?? 0 }}</el-tag></el-space><el-table :data="closeShortTermReview.ladder?.distribution ?? []" size="small" class="section-gap"><el-table-column prop="board_count" label="高度"/><el-table-column prop="count" label="数量"/></el-table></el-card></el-col>
        <el-col :md="8" :xs="24"><el-card shadow="never" header="板块主攻与覆盖"><el-table :data="closeShortTermReview.sector_structure?.candidate_mainlines ?? []" size="small" max-height="210"><el-table-column prop="label" label="板块" min-width="105"/><el-table-column prop="net_inflow" label="净流" width="90"/><el-table-column prop="limit_like_top_stock_count" label="强势数" width="72"/><el-table-column prop="mapped_members" label="成员" width="62"/></el-table><el-text type="info">完整板块 {{ closeShortTermReview.sector_structure?.complete_board_count ?? 0 }} 个；未映射板块不推断涨停结构。</el-text></el-card></el-col>
        <el-col :md="8" :xs="24"><el-card shadow="never" header="龙虎榜与亏钱效应"><el-descriptions :column="1" border size="small"><el-descriptions-item label="龙虎榜股票">{{ closeShortTermReview.capital_and_lhb?.lhb_stock_count ?? 0 }}</el-descriptions-item><el-descriptions-item label="净买 / 净卖">{{ closeShortTermReview.capital_and_lhb?.lhb_positive_net_count ?? 0 }} / {{ closeShortTermReview.capital_and_lhb?.lhb_negative_net_count ?? 0 }}</el-descriptions-item><el-descriptions-item label="机构席位记录">{{ closeShortTermReview.capital_and_lhb?.tushare_institution_records ?? 0 }}</el-descriptions-item><el-descriptions-item label="昨日涨停深跌">{{ closeShortTermReview.loss_effect?.previous_limit_deep_loss_count ?? 0 }}</el-descriptions-item><el-descriptions-item label="炸板 / 冲高回落">{{ closeShortTermReview.loss_effect?.limit_open_count ?? 0 }} / {{ closeShortTermReview.loss_effect?.intraday_reversal_count ?? 0 }}</el-descriptions-item><el-descriptions-item label="全市场下跌数">{{ closeShortTermReview.loss_effect?.negative_daily_count ?? 0 }}</el-descriptions-item></el-descriptions><el-space wrap class="section-gap"><el-tag v-for="flag in closeShortTermReview.loss_effect?.risk_flags ?? []" :key="flag" type="warning">{{ flag }}</el-tag></el-space></el-card></el-col>
      </el-row>
      <el-divider content-position="left">风向标与次日计划</el-divider>
      <el-table :data="closeShortTermReview.wind_flags ?? []" size="small" max-height="260"><el-table-column prop="symbol" label="代码" width="100"/><el-table-column prop="name" label="名称" width="100"/><el-table-column prop="type" label="类型" width="145"/><el-table-column prop="board_count" label="连板" width="65"/><el-table-column prop="reason" label="观察理由" min-width="240" show-overflow-tooltip/><el-table-column prop="next_session_trigger" label="次日触发" min-width="240" show-overflow-tooltip/><el-table-column prop="invalidation" label="失效条件" min-width="220" show-overflow-tooltip/></el-table>
      <el-alert class="section-gap" :title="closeShortTermReview.next_session_plan?.participation ?? '等待次日预案'" type="info" :closable="false" show-icon/>
      <el-space wrap><el-tag v-for="trigger in closeShortTermReview.next_session_plan?.triggers ?? []" :key="trigger" type="success">触发：{{ trigger }}</el-tag><el-tag v-for="invalid in closeShortTermReview.next_session_plan?.invalidations ?? []" :key="invalid" type="warning">失效：{{ invalid }}</el-tag></el-space>
      <el-alert class="section-gap" title="七步复盘仅生成研究清单，不自动加入观察池、不改变盘中阈值、不生成订单。" type="warning" :closable="false" show-icon/>
    </template>
  </el-card>
  <el-card shadow="never" class="board-flow-card">
    <template #header><div class="card-header"><div><span>市场量能与资金状态</span><small class="realtime-refresh-time">分钟东财板块流、腾讯全A量能与盘后Tushare资金流分层保存；当前只进入研究证据，不影响飞书策略阈值。</small></div><el-tag :type="marketFlowStateType(marketFlowLatest?.market_state)">{{ marketFlowStateLabel(marketFlowLatest?.market_state) }}</el-tag></div></template>
    <el-alert v-if="marketFlowError" :title="`量能资金特征读取失败：${marketFlowError}`" type="error" :closable="false" show-icon/>
    <template v-else>
      <el-row :gutter="12">
        <el-col :md="4" :xs="12"><el-statistic title="概念覆盖" :value="marketFlowLatest?.concept_count ?? 0"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="流入广度%" :value="marketFlowLatest?.concept_positive_ratio == null ? 0 : Math.round(Number(marketFlowLatest.concept_positive_ratio) * 1000) / 10"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="5分钟变化pct" :value="marketFlowLatest?.five_minute_positive_ratio_delta == null ? 0 : Math.round(Number(marketFlowLatest.five_minute_positive_ratio_delta) * 1000) / 10"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="日内漂移pct" :value="marketFlowLatest?.session_positive_ratio_delta == null ? 0 : Math.round(Number(marketFlowLatest.session_positive_ratio_delta) * 1000) / 10"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="成交额变化%" :value="marketFlowLatest?.amount_change_pct ?? 0"/></el-col>
        <el-col :md="4" :xs="12"><el-statistic title="成交量变化%" :value="marketFlowLatest?.volume_change_pct ?? 0"/></el-col>
      </el-row>
      <el-space wrap class="section-gap"><el-tag :type="marketFlowLatest?.status === 'ready' ? 'success' : 'warning'">{{ marketFlowLatest?.status ?? '等待采样' }}</el-tag><el-tag v-for="flag in marketFlowLatest?.quality_flags ?? []" :key="flag" type="warning" size="small">{{ flag }}</el-tag><el-tag type="info">晋级门禁 {{ marketFlow.research_gate?.observed_trading_days ?? 0 }}/{{ marketFlow.research_gate?.minimum_trading_days ?? 60 }}日 · {{ marketFlow.research_gate?.matured_independent_events ?? 0 }}/{{ marketFlow.research_gate?.minimum_independent_events ?? 200 }}成熟事件</el-tag></el-space>
      <el-empty v-if="!marketFlow.items.length" description="所选日期尚无量能资金特征；原始板块曲线仍可单独查看" :image-size="54"/>
      <v-chart v-else :option="marketFlowChartOption" autoresize class="market-flow-state-chart"/>
      <el-table v-if="marketFlow.daily?.length" :data="marketFlow.daily" max-height="220" size="small" class="section-gap">
        <el-table-column prop="exchange_date" label="交易日" width="105"/>
        <el-table-column label="状态" width="105"><template #default="{ row }"><el-tag size="small" :type="marketFlowStateType(row.market_state)">{{ marketFlowStateLabel(row.market_state) }}</el-tag></template></el-table-column>
        <el-table-column label="上涨广度" width="95"><template #default="{ row }">{{ row.advancer_ratio == null ? '-' : `${(Number(row.advancer_ratio) * 100).toFixed(1)}%` }}</template></el-table-column>
        <el-table-column label="板块流入广度" width="110"><template #default="{ row }">{{ row.concept_positive_ratio == null ? '-' : `${(Number(row.concept_positive_ratio) * 100).toFixed(1)}%` }}</template></el-table-column>
        <el-table-column label="成交额变化" width="100"><template #default="{ row }">{{ row.amount_change_pct == null ? '-' : `${Number(row.amount_change_pct).toFixed(1)}%` }}</template></el-table-column>
        <el-table-column label="成交量变化" width="100"><template #default="{ row }">{{ row.volume_change_pct == null ? '-' : `${Number(row.volume_change_pct).toFixed(1)}%` }}</template></el-table-column>
        <el-table-column label="质量" min-width="180"><template #default="{ row }"><el-space wrap><el-tag v-for="flag in row.quality_flags ?? []" :key="flag" size="small" type="warning">{{ flag }}</el-tag></el-space></template></el-table-column>
      </el-table>
      <el-divider content-position="left">跨日板块资金迁移与龙虎榜联动 Top20</el-divider>
      <el-empty v-if="!marketFlowSectorHighlights.length" description="该日尚无收盘同花顺资金流特征；缺失不会补零" :image-size="48"/>
      <el-table v-else :data="marketFlowSectorHighlights" max-height="340" size="small">
        <el-table-column prop="label" label="概念板块" min-width="145"/>
        <el-table-column label="迁移" width="105"><template #default="{ row }"><el-tag size="small" :type="sectorFlowTransitionType(row.transition)">{{ sectorFlowTransitionLabel(row.transition) }}</el-tag></template></el-table-column>
        <el-table-column label="当日净流" width="105"><template #default="{ row }">{{ displayValue(row.net_amount) }}</template></el-table-column>
        <el-table-column label="较前日变化" width="110"><template #default="{ row }">{{ displayValue(row.net_change_amount) }}</template></el-table-column>
        <el-table-column label="连续方向" width="88"><template #default="{ row }">{{ row.flow_sign_streak > 0 ? `流入${row.flow_sign_streak}日` : row.flow_sign_streak < 0 ? `流出${Math.abs(row.flow_sign_streak)}日` : '-' }}</template></el-table-column>
        <el-table-column label="板块涨跌" width="90"><template #default="{ row }">{{ row.change_pct == null ? '-' : `${Number(row.change_pct).toFixed(2)}%` }}</template></el-table-column>
        <el-table-column prop="lhb_stock_count" label="龙虎榜股" width="82"/>
        <el-table-column label="龙虎净买" width="105"><template #default="{ row }">{{ displayValue(row.lhb_net_amount) }}</template></el-table-column>
        <el-table-column prop="limit_up_count" label="涨停数" width="72"/>
        <el-table-column label="证据" width="135"><template #default="{ row }"><el-tag size="small" type="info">{{ row.provider_key }}</el-tag></template></el-table-column>
      </el-table>
      <el-divider content-position="left">板块状态后续响应（只用于研究）</el-divider>
      <el-table v-if="marketFlow.sector_outcome_summary?.length" :data="marketFlow.sector_outcome_summary" max-height="260" size="small">
        <el-table-column label="状态" width="105"><template #default="{ row }"><el-tag size="small" :type="sectorFlowTransitionType(row.transition)">{{ sectorFlowTransitionLabel(row.transition) }}</el-tag></template></el-table-column>
        <el-table-column prop="horizon_days" label="后续观测日" width="90"/>
        <el-table-column prop="matured" label="成熟样本" width="88"/>
        <el-table-column label="方向命中" width="95"><template #default="{ row }">{{ row.directional_hit_rate == null ? '-' : `${(Number(row.directional_hit_rate) * 100).toFixed(1)}%` }}</template></el-table-column>
        <el-table-column label="方向收益" width="100"><template #default="{ row }">{{ row.avg_directional_return == null ? '-' : `${(Number(row.avg_directional_return) * 100).toFixed(2)}%` }}</template></el-table-column>
        <el-table-column label="横截面超额" width="110"><template #default="{ row }">{{ row.avg_excess_return == null ? '-' : `${(Number(row.avg_excess_return) * 100).toFixed(2)}%` }}</template></el-table-column>
      </el-table>
      <el-text type="info" class="review-note">{{ marketFlow.notice }}</el-text>
    </template>
  </el-card>
  <el-card shadow="never" class="board-flow-card" v-loading="boardFlowLoading">
    <template #header><div class="card-header"><div><span>盘中板块资金分钟曲线</span><small class="realtime-refresh-time">每 60 秒自动增量刷新并检测轮动；红/绿突出当前净流入/净流出各前 10，其余板块仍完整显示。完整 Top10 快报另按五分钟节流。</small></div><el-space wrap><el-date-picker v-model="boardFlowDate" type="date" value-format="YYYY-MM-DD" size="small" class="board-flow-date" @change="resetBoardFlowCurves"/><el-radio-group v-model="boardFlowTaxonomy" size="small" @change="resetBoardFlowCurves"><el-radio-button value="industry">行业</el-radio-button><el-radio-button value="concept">概念</el-radio-button></el-radio-group><el-button :icon="Refresh" size="small" @click="loadBoardFlowCurves(false)">增量刷新</el-button></el-space></div></template>
    <el-alert v-if="boardFlowError" :title="`板块曲线读取失败：${boardFlowError}`" type="error" :closable="false" show-icon/>
    <template v-else>
      <div class="board-flow-toolbar"><el-space wrap><el-tag type="info">{{ boardFlowSeriesRows.length }} 个板块</el-tag><el-tag type="success">{{ boardFlowWindowText }}</el-tag><el-tag :type="boardFlowLatestSnapshot?.coverage ? 'success' : 'warning'">最新覆盖 {{ boardFlowLatestSnapshot?.coverage ?? 0 }}</el-tag><el-tag type="info">最后真实点 {{ chinaDateTime(boardFlowLatestSnapshot?.observed_at) }}</el-tag><el-tag v-if="boardFlowGaps" type="warning">{{ boardFlowGaps }} 段缺口已补点</el-tag></el-space><el-select v-model="boardFlowFocus" multiple filterable clearable collapse-tags collapse-tags-tooltip placeholder="可选重点板块；留空显示全部" class="board-flow-focus"><el-option v-for="item in boardFlowSeriesRows" :key="`${item.taxonomy_key}:${item.sector_key}`" :label="item.label" :value="`${item.taxonomy_key}:${item.sector_key}`"/></el-select></div>
      <el-empty v-if="!boardFlowSeriesRows.length" description="所选日期尚无板块分钟快照" :image-size="68"/>
      <v-chart v-else :option="boardFlowChartOption" autoresize class="board-flow-chart"/>
      <el-text type="info" class="review-note">{{ boardFlowNotice || '时间轴以 Asia/Shanghai 交易所时钟生成；缺失分钟沿用最近真实值，悬浮时会标记为补点。' }}</el-text>
      <el-divider content-position="left">一分钟资金轮动事件</el-divider>
      <el-alert title="每 60 秒比较相邻同源快照：同类板块资金变化进入前 5%、变化不少于 2 亿元且当前净流绝对值不少于 1 亿元时入队；流出转流入、流入转流出和单向急剧加速均需下一分钟方向保持。事件只进入前端研究证据，不发送飞书。" type="info" :closable="false" show-icon/>
      <el-empty v-if="!boardRotationEvents.length" description="本交易日尚无满足阈值的板块轮动事件" :image-size="52" class="section-gap"/>
      <el-table v-else :data="boardRotationEvents" max-height="300" size="small" class="section-gap">
        <el-table-column label="观测时间" width="132"><template #default="{ row }">{{ chinaDateTime(row.last_observed_at) }}</template></el-table-column>
        <el-table-column prop="label" label="板块" min-width="125" show-overflow-tooltip/>
        <el-table-column label="轮动" width="105"><template #default="{ row }"><el-tag size="small" :type="row.direction === 'inflow' ? 'success' : 'danger'">{{ boardRotationKind(row) }}</el-tag></template></el-table-column>
        <el-table-column label="一分钟净流变化" width="130"><template #default="{ row }">{{ Number(row.conditions?.previous_net_inflow ?? 0).toFixed(2) }} → {{ Number(row.conditions?.current_net_inflow ?? 0).toFixed(2) }} 亿</template></el-table-column>
        <el-table-column label="状态" width="122"><template #default="{ row }"><el-tag size="small" :type="boardRotationStateType(row.state)">{{ boardRotationStateText(row.state) }}</el-tag></template></el-table-column>
        <el-table-column label="通知范围" width="120"><template #default="{ row }"><el-tag size="small" type="info">{{ boardRotationDeliveryText(row) }}</el-tag></template></el-table-column>
      </el-table>
    </template>
  </el-card>
  <el-card shadow="never" class="section-gap">
    <template #header><div class="card-header"><div><span>板块流向个股挖掘</span><small class="realtime-refresh-time">随五分钟板块快报自动更新；只使用精确成分映射完整且腾讯同刻报价齐全的板块。仅展示在研究台，不发送飞书。</small></div><el-tag :type="boardStockMining.run?.status === 'completed' ? 'success' : 'info'">{{ boardStockMining.run?.status ?? '等待快照' }}</el-tag></div></template>
    <el-alert :title="boardStockMining.notice ?? '研究候选由板块资金、个股主力流、量比、换手和价格结构共同筛出；不是买卖指令。'" type="info" :closable="false" show-icon/>
    <el-descriptions v-if="boardStockMining.run" :column="mobileLayout ? 1 : 4" border size="small" class="section-gap"><el-descriptions-item label="观测时间">{{ chinaDateTime(boardStockMining.run.observed_at) }}</el-descriptions-item><el-descriptions-item label="完整板块">{{ boardStockMining.run.coverage?.exact_complete_boards ?? 0 }}</el-descriptions-item><el-descriptions-item label="流入 / 流出">{{ boardStockMining.run.summary?.inflow_candidates ?? 0 }} / {{ boardStockMining.run.summary?.outflow_candidates ?? 0 }}</el-descriptions-item><el-descriptions-item label="跳过不完整映射">{{ boardStockMining.run.coverage?.partial_or_unmapped_boards_skipped ?? 0 }}</el-descriptions-item></el-descriptions>
    <el-tabs type="border-card" class="section-gap">
      <el-tab-pane :label="`流入启动 ${boardStockMining.inflow?.length ?? 0}`"><el-empty v-if="!(boardStockMining.inflow?.length)" description="当前无满足严格活动门槛的流入候选" :image-size="52"/><el-table v-else :data="boardStockMining.inflow" max-height="320" size="small"><el-table-column prop="rank" label="#" width="44"/><el-table-column prop="symbol" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="88"/><el-table-column prop="label" label="精确板块" min-width="120"/><el-table-column prop="setup_key" label="结构" min-width="145"/><el-table-column label="板块净流" width="105"><template #default="{ row }">{{ displayValue(row.board_net_inflow) }}</template></el-table-column><el-table-column label="主力流" width="100"><template #default="{ row }">{{ displayValue(row.main_net_inflow) }}</template></el-table-column><el-table-column label="量比/换手" width="102"><template #default="{ row }">{{ displayValue(row.volume_ratio) }} / {{ displayValue(row.turnover_rate) }}%</template></el-table-column><el-table-column label="涨跌" width="72"><template #default="{ row }">{{ displayValue(row.pct_change) }}%</template></el-table-column><el-table-column prop="score" label="筛选分" width="80"/><el-table-column label="研究" width="72" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.symbol)">分析</el-button></template></el-table-column></el-table></el-tab-pane>
      <el-tab-pane :label="`流出风险 ${boardStockMining.outflow?.length ?? 0}`"><el-empty v-if="!(boardStockMining.outflow?.length)" description="当前无满足严格活动门槛的流出风险候选" :image-size="52"/><el-table v-else :data="boardStockMining.outflow" max-height="320" size="small"><el-table-column prop="rank" label="#" width="44"/><el-table-column prop="symbol" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="88"/><el-table-column prop="label" label="精确板块" min-width="120"/><el-table-column prop="setup_key" label="结构" min-width="145"/><el-table-column label="板块净流" width="105"><template #default="{ row }">{{ displayValue(row.board_net_inflow) }}</template></el-table-column><el-table-column label="主力流" width="100"><template #default="{ row }">{{ displayValue(row.main_net_inflow) }}</template></el-table-column><el-table-column label="量比/换手" width="102"><template #default="{ row }">{{ displayValue(row.volume_ratio) }} / {{ displayValue(row.turnover_rate) }}%</template></el-table-column><el-table-column label="涨跌" width="72"><template #default="{ row }">{{ displayValue(row.pct_change) }}%</template></el-table-column><el-table-column prop="score" label="风险分" width="80"/><el-table-column label="研究" width="72" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.symbol)">分析</el-button></template></el-table-column></el-table></el-tab-pane>
    </el-tabs>
  </el-card>
  <el-card shadow="never" class="section-gap">
    <template #header><div class="card-header"><div><span>涨停关联股挖掘</span><small class="realtime-refresh-time">涨停事实 → 同花顺精确概念关联 → 腾讯同刻量价；已排除接近涨停的追板对象。仅展示在研究台，不发送飞书。</small></div><el-tag :type="limitLinkageMining.run?.status === 'completed' ? 'success' : 'info'">{{ limitLinkageMining.run?.status ?? '等待涨停池' }}</el-tag></div></template>
    <el-alert :title="limitLinkageMining.notice ?? '仅做板块内关联研究；必须再经分钟级承接确认，不能替代交易决策。'" type="warning" :closable="false" show-icon/>
    <el-descriptions v-if="limitLinkageMining.run" :column="mobileLayout ? 1 : 4" border size="small" class="section-gap"><el-descriptions-item label="观测时间">{{ chinaDateTime(limitLinkageMining.run.observed_at) }}</el-descriptions-item><el-descriptions-item label="涨停锚点">{{ limitLinkageMining.run.summary?.anchors ?? 0 }}</el-descriptions-item><el-descriptions-item label="精确关联">{{ limitLinkageMining.run.summary?.exact_relation_rows ?? 0 }}</el-descriptions-item><el-descriptions-item label="候选数">{{ limitLinkageMining.run.summary?.candidate_count ?? 0 }}</el-descriptions-item></el-descriptions>
    <el-empty v-if="!(limitLinkageMining.items?.length)" description="等待同一交易日涨停池与同刻行情同时满足严格条件" :image-size="52" class="section-gap"/>
    <el-table v-else :data="limitLinkageMining.items" max-height="320" size="small" class="section-gap"><el-table-column prop="rank" label="#" width="44"/><el-table-column prop="symbol" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="88"/><el-table-column label="涨停锚点" min-width="130"><template #default="{ row }">{{ (row.leader_names?.length ? row.leader_names : row.leader_symbols)?.join('、') ?? '-' }}</template></el-table-column><el-table-column label="共享概念" min-width="150"><template #default="{ row }">{{ row.shared_concepts }} · {{ row.concept_labels?.slice(0, 2).join('、') ?? '-' }}</template></el-table-column><el-table-column label="主力流" width="100"><template #default="{ row }">{{ displayValue(row.main_net_inflow) }}</template></el-table-column><el-table-column label="量比/换手" width="102"><template #default="{ row }">{{ displayValue(row.volume_ratio) }} / {{ displayValue(row.turnover_rate) }}%</template></el-table-column><el-table-column label="涨跌" width="72"><template #default="{ row }">{{ displayValue(row.pct_change) }}%</template></el-table-column><el-table-column prop="score" label="研究分" width="80"/><el-table-column label="研究" width="72" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.symbol)">分析</el-button></template></el-table-column></el-table>
  </el-card>
  <el-card v-if="closeIndexRegime" shadow="never" header="多指数纠错反弹 / B浪情景核验">
    <el-alert :title="closeIndexRegime.interpretation ?? '多指数仅用于判断市场环境；B浪只是分析师情景标签，不直接触发个股买卖。'" :type="indexRegimeType" :closable="false" show-icon/>
    <el-table :data="closeIndexRegime.items ?? []" max-height="300" size="small" class="section-gap">
      <el-table-column label="指数" min-width="105"><template #default="{ row }">{{ indexLabel(row.symbol) }}</template></el-table-column>
      <el-table-column prop="trading_date" label="交易日" width="105"/>
      <el-table-column prop="close" label="收盘" width="90"/>
      <el-table-column label="区间回撤" width="100"><template #default="{ row }">{{ displayValue(row.drawdown_high_to_low_pct) }}%</template></el-table-column>
      <el-table-column label="低点反弹" width="100"><template #default="{ row }">{{ displayValue(row.rebound_from_low_pct) }}%</template></el-table-column>
      <el-table-column label="距高点" width="90"><template #default="{ row }">{{ displayValue(row.versus_period_high_pct) }}%</template></el-table-column>
      <el-table-column label="区间修复" width="95"><template #default="{ row }">{{ outcomePercent(row.range_retracement) }}</template></el-table-column>
      <el-table-column label="近5日" width="85"><template #default="{ row }">{{ displayValue(row.return_5_sessions_pct) }}%</template></el-table-column>
      <el-table-column label="量能比" width="85"><template #default="{ row }">{{ displayValue(row.volume_ratio_5_vs_prior15) }}</template></el-table-column>
    </el-table>
  </el-card>
  <el-card shadow="never"><template #header><div class="card-header"><span>复盘证据与成员回填</span><el-space><el-button :loading="actionLoading === '补齐一批概念成员'" @click="advanceConceptBackfill">补齐一批成员</el-button><el-button type="primary" :loading="actionLoading === '保存收盘板块复盘'" @click="refreshCloseReview">保存/刷新复盘</el-button></el-space></div></template>
    <el-descriptions :column="mobileLayout ? 1 : 4" border size="small"><el-descriptions-item label="资金流交易日">{{ conceptBackfill.trade_date ?? '-' }}</el-descriptions-item><el-descriptions-item label="当前精确映射"><el-tag :type="conceptBackfill.complete ? 'success' : 'warning'">{{ conceptBackfill.mapped_concepts }} / {{ conceptBackfill.total_concepts }}</el-tag><el-text v-if="conceptBackfill.mapping_evidence?.latest_available_at" type="info" size="small"> · {{ chinaDateTime(conceptBackfill.mapping_evidence.latest_available_at) }}</el-text></el-descriptions-item><el-descriptions-item label="同日同步回执"><el-tag :type="conceptBackfill.receipt_complete ? 'success' : 'info'">{{ conceptBackfill.receipt_mapped_concepts ?? 0 }} / {{ conceptBackfill.total_concepts }}</el-tag></el-descriptions-item><el-descriptions-item label="自动回填">{{ conceptBackfill.automatic?.enabled ? `开启（每批 ${conceptBackfill.automatic.batch_size}）` : '关闭' }}</el-descriptions-item><el-descriptions-item label="证据状态" :span="mobileLayout ? 1 : 4"><el-space wrap><el-tag v-for="item in conceptBackfill.states" :key="item.state" :type="item.state === 'completed' || item.state === 'active_exact_mapping' ? 'success' : item.state === 'failed' ? 'danger' : 'info'">{{ item.state }} {{ item.boards }}</el-tag></el-space></el-descriptions-item></el-descriptions>
    <el-text type="info" class="section-gap review-note">{{ conceptBackfill.notice }}</el-text>
  </el-card>
  <el-card shadow="never"><template #header><div class="card-header"><span>盘后蓄势与首动候选池</span><el-space><el-tag :type="postCloseStrategyRun?.status === 'completed' ? 'success' : postCloseStrategyRun?.status === 'blocked' ? 'warning' : 'info'">{{ postCloseStrategyRun?.status ?? '未运行' }}</el-tag><el-button type="primary" :loading="actionLoading === '运行盘后蓄势与首动筛选'" @click="runPostCloseStrategy">运行盘后策略</el-button></el-space></div></template>
    <el-alert title="自动任务每天上海时间 18:55--19:10 在已落库日线完整时运行；30 日蓄势是严格结构，15 日结果仅用于历史积累期的观察，不自动加入观察池或下单。" type="info" :closable="false" show-icon/>
    <el-descriptions v-if="postCloseStrategyRun" :column="mobileLayout ? 1 : 4" border size="small" class="section-gap"><el-descriptions-item label="交易日">{{ postCloseStrategyRun.as_of_date ?? '-' }}</el-descriptions-item><el-descriptions-item label="模型">{{ postCloseStrategyRun.model_version ?? '-' }}</el-descriptions-item><el-descriptions-item label="日线覆盖">{{ displayValue(postCloseStrategyRun.source_status?.daily_symbols) }}</el-descriptions-item><el-descriptions-item label="返回候选">{{ displayValue(postCloseStrategyRun.summary?.returned) }}</el-descriptions-item></el-descriptions>
    <el-empty v-if="postCloseStrategyRun && !postCloseCandidates.length" description="当前没有满足严格门槛的候选，或日线历史仍不足" :image-size="58" class="section-gap"/>
    <el-table v-else :data="postCloseCandidates" max-height="420" size="small" class="section-gap"><el-table-column prop="rank" label="#" width="48"/><el-table-column prop="symbol" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="95"/><el-table-column label="类型" width="118"><template #default="{ row }"><el-tag size="small" :type="postCloseCandidateType(row.candidate_type)">{{ postCloseCandidateLabel(row.candidate_type) }}</el-tag></template></el-table-column><el-table-column prop="score" label="分数" width="75"/><el-table-column label="收盘结构" min-width="220"><template #default="{ row }">{{ row.structure?.notice ?? row.structure?.status ?? '-' }}</template></el-table-column><el-table-column label="精确概念" min-width="125"><template #default="{ row }">{{ row.board_context?.exact_member_mapping ? row.board_context?.label ?? '已映射' : '无精确映射' }}</template></el-table-column><el-table-column label="板块流" width="95"><template #default="{ row }">{{ displayValue(row.board_context?.net_amount) }}</template></el-table-column><el-table-column label="有效期" min-width="142"><template #default="{ row }">{{ row.expires_at ? dateText(row.expires_at) : '待人工复核' }}</template></el-table-column><el-table-column label="来源覆盖" min-width="120"><template #default="{ row }">日线 {{ row.source_snapshot?.daily_symbols ?? '-' }} / 板块 {{ row.source_snapshot?.exact_board_context_symbols ?? '-' }}</template></el-table-column><el-table-column label="风险/原因" min-width="190"><template #default="{ row }"><el-space wrap><el-tag v-for="flag in (row.reason_codes?.length ? row.reason_codes : row.risk_flags ?? [])" :key="flag" size="small" type="warning">{{ flag }}</el-tag></el-space></template></el-table-column><el-table-column label="研究" width="86" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.symbol)">技术分析</el-button></template></el-table-column></el-table>
  </el-card>
  <TenDayLeaderRotationPanel :data="tenDayLeaderRotation" :loading="actionLoading === '重算十日排行榜影子池'" @run="runTenDayLeaderRotation"/>
  <el-card shadow="never"><template #header><div class="card-header"><span>龙头/连板/首板分钟拉升形态</span><el-space><el-tag :type="strategyPatternRun?.status === 'completed' ? 'success' : strategyPatternRun?.status === 'partial' ? 'warning' : 'info'">{{ strategyPatternRun?.status ?? '未运行' }}</el-tag><el-button type="primary" :loading="actionLoading === '挖掘涨停拉升形态'" @click="runStrategyPatternMining">运行形态挖掘</el-button></el-space></div></template>
    <el-alert title="按同花顺涨停池和连板梯队分层，连接精确概念资金流、Super 日K及腾讯分钟量价。地天板只在深跌反抽、收复昨收、承接三个阶段分别标注，不直接给出买入指令。" type="warning" :closable="false" show-icon/>
    <el-alert v-if="strategyPoolCoverage.notice" :title="strategyPoolCoverage.notice" :type="strategyPoolCoverage.status === 'two_source_union' ? 'success' : 'warning'" :closable="false" show-icon class="section-gap"/>
    <el-descriptions v-if="strategyPatternRun" :column="mobileLayout ? 1 : 6" border size="small" class="section-gap"><el-descriptions-item label="交易日">{{ strategyPatternRun.as_of_date ?? '-' }}</el-descriptions-item><el-descriptions-item label="模型">{{ strategyPatternRun.model_version ?? '-' }}</el-descriptions-item><el-descriptions-item label="并集涨停池">{{ strategyPoolCoverage.union_count ?? strategyLimitPool.length }} 只</el-descriptions-item><el-descriptions-item label="同花顺/东财/交集">{{ strategyPoolCoverage.tushare_count ?? '-' }} / {{ strategyPoolCoverage.eastmoney_count ?? '-' }} / {{ strategyPoolCoverage.intersection_count ?? '-' }}</el-descriptions-item><el-descriptions-item label="多板并集/梯级直出">{{ strategyPoolCoverage.multi_board_union_count ?? strategyLimitLadder.length }} / {{ strategyPoolCoverage.limit_step_count ?? '-' }}</el-descriptions-item><el-descriptions-item label="精选/回放完成">{{ strategyPatternPicks.length }} / {{ displayValue(strategyPatternRun.summary?.minute_completed) }}</el-descriptions-item></el-descriptions>
    <el-tabs type="border-card" class="section-gap">
      <el-tab-pane :label="`涨停池 ${strategyLimitPool.length}`">
        <el-table :data="strategyLimitPool" max-height="500" size="small"><el-table-column prop="rank" label="#" width="46"/><el-table-column prop="ts_code" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="92"/><el-table-column prop="tag" label="梯队" width="90"/><el-table-column label="来源" width="96"><template #default="{ row }"><el-tag size="small" :type="(row.sources?.length ?? 0) >= 2 ? 'success' : 'warning'">{{ (row.sources?.length ?? 0) >= 2 ? '双源' : '单源' }}</el-tag></template></el-table-column><el-table-column label="状态" width="82"><template #default="{ row }"><el-tag size="small" :type="row.status === '一字板' ? 'danger' : 'warning'">{{ row.status ?? '-' }}</el-tag></template></el-table-column><el-table-column label="涨幅" width="78"><template #default="{ row }">{{ displayValue(row.pct_chg) }}%</template></el-table-column><el-table-column label="换手" width="78"><template #default="{ row }">{{ displayValue(row.turnover_rate) }}%</template></el-table-column><el-table-column label="5日量" width="76"><template #default="{ row }">{{ displayValue(row.volume_multiple_5d) }}</template></el-table-column><el-table-column label="精确板块/净流" min-width="145"><template #default="{ row }">{{ row.board_context?.label ?? '-' }} / {{ displayValue(row.board_context?.net_amount) }}</template></el-table-column><el-table-column label="龙虎榜机构净额" width="120"><template #default="{ row }">{{ moneyWan(row.lhb_context?.institution_net_buy) }}</template></el-table-column><el-table-column prop="open_num" label="开板" width="68"/><el-table-column prop="limit_amount" label="封单金额" width="110"/><el-table-column label="封板率" width="82"><template #default="{ row }">{{ outcomePercent(row.limit_up_suc_rate) }}</template></el-table-column><el-table-column prop="lu_desc" label="涨停原因" min-width="250" show-overflow-tooltip/><el-table-column label="研究" width="86" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.ts_code)">技术分析</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane :label="`连板/多板 ${strategyLimitLadder.length}`">
        <el-table :data="strategyLimitLadder" max-height="500" size="small"><el-table-column prop="rank" label="#" width="46"/><el-table-column prop="ts_code" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="100"/><el-table-column label="板数" width="82"><template #default="{ row }"><el-tag type="danger" size="small">{{ row.nums }} 板</el-tag></template></el-table-column><el-table-column prop="tag" label="区间梯队" width="95"/><el-table-column label="梯级来源" width="100"><template #default="{ row }"><el-tag size="small" :type="row.ladder_sources?.includes('tushare_limit_step') ? 'success' : 'info'">{{ row.ladder_sources?.includes('tushare_limit_step') ? '梯级直出' : '多板补齐' }}</el-tag></template></el-table-column><el-table-column prop="status" label="封板状态" width="90"/><el-table-column label="涨幅" width="78"><template #default="{ row }">{{ displayValue(row.pct_chg) }}%</template></el-table-column><el-table-column label="换手" width="78"><template #default="{ row }">{{ displayValue(row.turnover_rate) }}%</template></el-table-column><el-table-column label="5日量" width="76"><template #default="{ row }">{{ displayValue(row.volume_multiple_5d) }}</template></el-table-column><el-table-column label="板块/净流" min-width="135"><template #default="{ row }">{{ row.board_context?.label ?? '-' }} / {{ displayValue(row.board_context?.net_amount) }}</template></el-table-column><el-table-column label="龙虎榜机构净额" width="120"><template #default="{ row }">{{ moneyWan(row.lhb_context?.institution_net_buy) }}</template></el-table-column><el-table-column prop="open_num" label="开板" width="68"/><el-table-column prop="limit_amount" label="封单金额" width="110"/><el-table-column prop="lu_desc" label="涨停原因" min-width="250" show-overflow-tooltip/><el-table-column label="研究" width="86" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.ts_code)">技术分析</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane :label="`连板延续观察 ${strategyContinuationCandidates.length}`">
        <el-alert title="仅在盘后最终涨停池可用时，筛选至少 2 板且封单/流通市值不低于 1.5% 的下一交易日复核样本。它不是盘中追板，也不生成订单；开盘必须再次检查可交易性、集合竞价、分钟承接与板块状态。" type="warning" :closable="false" show-icon/>
        <el-table :data="strategyContinuationCandidates" max-height="500" size="small" class="section-gap"><el-table-column label="#" width="46"><template #default="{ row }">{{ row.continuation_watch?.rank ?? '-' }}</template></el-table-column><el-table-column prop="ts_code" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="95"/><el-table-column prop="tag" label="梯队" width="95"/><el-table-column label="封单/流通" width="100"><template #default="{ row }">{{ outcomePercent(row.continuation_watch?.seal_to_float) }}</template></el-table-column><el-table-column label="换手" width="76"><template #default="{ row }">{{ displayValue(row.turnover_rate) }}%</template></el-table-column><el-table-column prop="open_num" label="开板" width="68"/><el-table-column label="封板率" width="82"><template #default="{ row }">{{ outcomePercent(row.limit_up_suc_rate) }}</template></el-table-column><el-table-column label="板块/净流" min-width="145"><template #default="{ row }">{{ row.board_context?.label ?? '-' }} / {{ displayValue(row.board_context?.net_amount) }}</template></el-table-column><el-table-column prop="lu_desc" label="涨停原因" min-width="240" show-overflow-tooltip/><el-table-column label="风险" min-width="200"><template #default="{ row }"><el-space wrap><el-tag v-for="flag in row.continuation_watch?.risk_flags ?? []" :key="flag" size="small" type="warning">{{ flag }}</el-tag></el-space></template></el-table-column><el-table-column label="研究" width="86" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.ts_code)">技术分析</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane :label="`龙头梯队复核 ${strategyDragonLeaderCandidates.length}`">
        <el-alert title="龙头位次只来自当前已落库的涨停池并集。市场宽度、题材梯队、竞价和盘口均有覆盖边界；本页只生成下一交易日人工复核清单，不提供买卖指令。" type="warning" :closable="false" show-icon/>
        <el-descriptions :column="mobileLayout ? 1 : 4" border size="small" class="section-gap"><el-descriptions-item label="可观察涨停数">{{ strategyDragonLeaderMarket?.observable_limit_up_count ?? '-' }}</el-descriptions-item><el-descriptions-item label="可观察连板数">{{ strategyDragonLeaderMarket?.observable_multi_board_count ?? '-' }}</el-descriptions-item><el-descriptions-item label="最高梯队">{{ strategyDragonLeaderMarket?.highest_observed_streak ?? '-' }}</el-descriptions-item><el-descriptions-item label="市场状态">{{ strategyDragonLeaderMarket?.market_state ?? 'unavailable' }}</el-descriptions-item></el-descriptions>
        <el-alert title="龙头影子评分与研究策略" :description="`仅研究展示：首个候选 ${strategyDragonLeaderCandidates[0]?.dragon_leader_watch?.score_shadow?.score ?? '-'} / ${strategyDragonLeaderCandidates[0]?.dragon_leader_watch?.score_shadow?.max_available_score ?? '-'}；研究策略覆盖 2进3 新龙选拔、同梯队卡位、高位放量弱分歧。晋级率、炸板修复率、竞价和盘中确认缺失时不具备可比性，不影响实时规则。`" type="info" :closable="false" show-icon class="section-gap"/>
        <el-table :data="strategyDragonLeaderCandidates" max-height="500" size="small"><el-table-column label="#" width="46"><template #default="{ row }">{{ row.dragon_leader_watch?.rank ?? '-' }}</template></el-table-column><el-table-column prop="ts_code" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="95"/><el-table-column prop="tag" label="梯队" width="92"/><el-table-column label="梯队位次" width="88"><template #default="{ row }">{{ row.dragon_leader_watch?.leader_rank ?? '-' }}</template></el-table-column><el-table-column label="复核层级" min-width="140"><template #default="{ row }"><el-tag size="small" type="info">{{ row.dragon_leader_watch?.review_tier ?? '-' }}</el-tag></template></el-table-column><el-table-column label="题材梯队" min-width="175"><template #default="{ row }">{{ row.dragon_leader_watch?.theme_context?.label ?? '未映射' }} / {{ row.dragon_leader_watch?.theme_context?.observable_multi_board_count ?? '-' }} 连板</template></el-table-column><el-table-column label="次日确认" min-width="130"><template #default="{ row }">{{ row.dragon_leader_watch?.session_confirmation?.status === 'not_observed' ? '待竞价与分钟承接' : row.dragon_leader_watch?.session_confirmation?.status ?? '-' }}</template></el-table-column><el-table-column label="风险/覆盖" min-width="220"><template #default="{ row }"><el-space wrap><el-tag v-for="flag in row.dragon_leader_watch?.risk_flags ?? []" :key="flag" size="small" type="warning">{{ flag }}</el-tag></el-space></template></el-table-column><el-table-column label="研究" width="86" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.ts_code)">技术分析</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane :label="`今日精选 ${strategyPatternPicks.length}`">
        <el-table :data="strategyPatternPicks" max-height="500" size="small"><el-table-column prop="rank" label="#" width="46"/><el-table-column prop="symbol" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="92"/><el-table-column label="复盘评分" width="86"><template #default="{ row }"><el-tag :type="row.limit_context?.review_tier === 'priority_review' ? 'success' : 'warning'">{{ displayValue(row.limit_context?.review_score) }}</el-tag></template></el-table-column><el-table-column label="层级" width="92"><template #default="{ row }">{{ reviewTierText(row.limit_context?.review_tier) }}</template></el-table-column><el-table-column label="梯队" width="90"><template #default="{ row }">{{ row.limit_context?.tag ?? '-' }}</template></el-table-column><el-table-column label="板块/净流" min-width="135"><template #default="{ row }">{{ row.board_context?.label ?? '-' }} / {{ displayValue(row.board_context?.net_amount) }}</template></el-table-column><el-table-column label="龙虎榜机构净额" width="120"><template #default="{ row }">{{ moneyWan(row.limit_context?.lhb_context?.institution_net_buy) }}</template></el-table-column><el-table-column label="5日量" width="76"><template #default="{ row }">{{ displayValue(row.daily_features?.volume_multiple_5d) }}</template></el-table-column><el-table-column label="入选依据" min-width="260"><template #default="{ row }">{{ row.limit_context?.selection_reasons?.join('；') || '-' }}</template></el-table-column><el-table-column label="风险" min-width="180"><template #default="{ row }"><el-space wrap><el-tag v-for="flag in row.risk_flags ?? []" :key="flag" type="warning" size="small">{{ flag }}</el-tag></el-space></template></el-table-column><el-table-column label="研究" width="86" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.symbol)">技术分析</el-button></template></el-table-column></el-table>
      </el-tab-pane>
      <el-tab-pane :label="`形态样本 ${strategyPatternSamples.length}`">
        <el-table :data="strategyPatternSamples" max-height="500" size="small"><el-table-column prop="rank" label="#" width="46"/><el-table-column prop="symbol" label="代码" width="104"/><el-table-column prop="name" label="名称" min-width="92"/><el-table-column label="主样本" width="105"><template #default="{ row }"><el-tag size="small" :type="row.primary_cohort === 'ground_to_sky' ? 'danger' : row.primary_cohort === 'consecutive_limit' ? 'warning' : 'info'">{{ patternCohortLabel(row.primary_cohort) }}</el-tag></template></el-table-column><el-table-column label="梯队/盘前→盘后位次" width="160"><template #default="{ row }">{{ row.limit_context?.tag ?? '-' }} / {{ row.limit_context?.preopen_limit_pool_rank ?? '-' }} → {{ row.limit_context?.limit_pool_market_rank ?? '-' }}</template></el-table-column><el-table-column label="精确板块" min-width="115"><template #default="{ row }">{{ row.board_context?.label ?? '未映射' }}</template></el-table-column><el-table-column label="低点→收盘" width="125"><template #default="{ row }">{{ displayValue(row.daily_features?.low_pct) }}% → {{ displayValue(row.daily_features?.close_pct) }}%</template></el-table-column><el-table-column label="5日量能倍数" width="105"><template #default="{ row }">{{ displayValue(row.daily_features?.volume_multiple_5d) }}</template></el-table-column><el-table-column label="首次异动" width="82"><template #default="{ row }">{{ row.intraday_pattern?.deep_reversal_impulse?.time ?? row.intraday_pattern?.deep_discount_stabilization?.time ?? row.intraday_pattern?.standard_ignition?.time ?? row.intraday_pattern?.opening_drive?.first_four_pct_time ?? '-' }}</template></el-table-column><el-table-column label="收复昨收/承接" width="125"><template #default="{ row }">{{ row.intraday_pattern?.previous_close_reclaim?.time ?? '-' }} / {{ row.intraday_pattern?.previous_close_acceptance?.time ?? '-' }}</template></el-table-column><el-table-column label="触板" width="72"><template #default="{ row }">{{ row.intraday_pattern?.limit_reclaim?.time ?? '-' }}</template></el-table-column><el-table-column label="形态" min-width="185"><template #default="{ row }"><el-space wrap><el-tag v-for="tag in row.intraday_pattern?.pattern_tags ?? []" :key="tag" size="small" type="info">{{ tag }}</el-tag></el-space></template></el-table-column><el-table-column label="研究" width="86" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.symbol)">技术分析</el-button></template></el-table-column></el-table>
      </el-tab-pane>
    </el-tabs>
  </el-card>
  <el-row :gutter="14"><el-col :md="14" :xs="24"><el-card shadow="never" header="同花顺概念资金流与精确成分覆盖"><el-table :data="reviewConceptBoards" max-height="500" size="small" @row-click="(row: BoardItem) => selectedReviewBoardKey = row.sector_key"><el-table-column prop="label" label="概念" min-width="140"/><el-table-column prop="net_inflow" label="净流入" width="105"/><el-table-column label="涨跌幅" width="84"><template #default="{ row }">{{ displayValue(row.change_pct) }}%</template></el-table-column><el-table-column prop="mapped_members" label="精确成员" width="92"/><el-table-column prop="quoted_members" label="腾讯匹配" width="92"/><el-table-column label="Top10" width="78"><template #default="{ row }"><el-tag size="small" :type="row.top_stocks.length >= 10 ? 'success' : 'warning'">{{ row.top_stocks.length }} 只</el-tag></template></el-table-column></el-table></el-card></el-col><el-col :md="10" :xs="24"><el-card shadow="never"><template #header><div class="card-header"><span>板块个股 Top10</span><el-select v-model="selectedReviewBoardKey" size="small" class="review-board-select"><el-option v-for="board in reviewConceptBoards" :key="board.sector_key" :label="board.label" :value="board.sector_key"/></el-select></div></template><el-empty v-if="!selectedReviewBoard" description="等待可复盘的精确成员映射" :image-size="58"/><template v-else><el-descriptions :column="2" size="small" border><el-descriptions-item label="概念">{{ selectedReviewBoard.label }}</el-descriptions-item><el-descriptions-item label="净流入">{{ displayValue(selectedReviewBoard.net_inflow) }}</el-descriptions-item></el-descriptions><el-table :data="selectedReviewBoardStocks" max-height="390" size="small" class="section-gap"><el-table-column prop="symbol" label="代码" width="96"/><el-table-column prop="name" label="名称" min-width="90"/><el-table-column prop="main_net_inflow" label="主力流" width="94"/><el-table-column prop="volume_ratio" label="量比" width="68"/><el-table-column prop="turnover_rate" label="换手" width="68"/><el-table-column label="涨跌" width="68"><template #default="{ row }">{{ displayValue(row.pct_change) }}%</template></el-table-column></el-table></template></el-card></el-col></el-row>
  <el-card shadow="never"><template #header><div class="card-header"><span>盘中信号结果与归因</span><el-button :loading="actionLoading === '结算盘中信号'" @click="settleIntradayOutcomes">结算已确认信号</el-button></div></template>
    <el-alert title="只结算 confirmed / alerted 信号。收益是信号后的可观察价格路径，不是成交回报；pending 表示后续报价或下一交易日收盘尚未到达。" type="info" :closable="false" show-icon/>
    <el-table :data="intradayOutcomeSummary" max-height="220" size="small" class="section-gap"><el-table-column prop="horizon_key" label="期限" width="105"/><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="outcomeStatusType(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column prop="rows" label="样本" width="86"/><el-table-column label="平均方向收益" width="135"><template #default="{ row }">{{ outcomePercent(row.avg_directional_return) }}</template></el-table-column><el-table-column label="平均 MFE" width="110"><template #default="{ row }">{{ outcomePercent(row.avg_mfe) }}</template></el-table-column><el-table-column label="平均 MAE" width="110"><template #default="{ row }">{{ outcomePercent(row.avg_mae) }}</template></el-table-column></el-table>
    <el-divider content-position="left">点时分层归因</el-divider>
    <el-alert title="分层统计按信号触发时已经可得的市场状态、板块/同伴联动、信号阶段和模型版本计算；不足 30 个成熟样本的分组只作描述，不用于调参。" type="warning" :closable="false" show-icon/>
    <el-descriptions :column="mobileLayout ? 1 : 3" border size="small" class="section-gap">
      <el-descriptions-item label="正式验证门禁"><el-tag :type="attributionValidationGate.status === 'ready_for_formal_validation' ? 'success' : 'warning'">{{ attributionValidationGate.status === 'ready_for_formal_validation' ? '可进入正式验证' : '积累中' }}</el-tag></el-descriptions-item>
      <el-descriptions-item label="独立成熟信号">{{ attributionValidationGate.matured_unique_signals }} / {{ attributionValidationGate.required_unique_signals }}</el-descriptions-item>
      <el-descriptions-item label="覆盖交易日">{{ attributionValidationGate.trading_days }} / {{ attributionValidationGate.required_trading_days }}</el-descriptions-item>
    </el-descriptions>
    <el-table :data="intradayAttributionSummary" max-height="380" size="small" class="section-gap">
      <el-table-column label="维度" width="100"><template #default="{ row }">{{ attributionDimensionLabel(row.dimension) }}</template></el-table-column>
      <el-table-column label="分组" min-width="165"><template #default="{ row }">{{ attributionCohortLabel(row.cohort) }}</template></el-table-column>
      <el-table-column prop="horizon_key" label="期限" width="72"/>
      <el-table-column label="成熟/全部" width="92"><template #default="{ row }">{{ row.matured }} / {{ row.rows }}</template></el-table-column>
      <el-table-column label="命中率" width="88"><template #default="{ row }">{{ outcomePercent(row.hit_rate) }}</template></el-table-column>
      <el-table-column label="平均方向收益" width="118"><template #default="{ row }">{{ outcomePercent(row.avg_directional_return) }}</template></el-table-column>
      <el-table-column label="MFE / MAE" width="145"><template #default="{ row }">{{ outcomePercent(row.avg_mfe) }} / {{ outcomePercent(row.avg_mae) }}</template></el-table-column>
      <el-table-column label="盈亏比" width="78"><template #default="{ row }">{{ row.payoff_ratio === null || row.payoff_ratio === undefined ? '-' : Number(row.payoff_ratio).toFixed(2) }}</template></el-table-column>
      <el-table-column label="样本门禁" width="108"><template #default="{ row }"><el-tag size="small" :type="attributionStatusType(row.evaluation_status)">{{ row.evaluation_status === 'cohort_reviewable' ? '可复核' : '仅描述' }}</el-tag></template></el-table-column>
    </el-table>
    <el-table :data="intradayOutcomes" max-height="360" size="small"><el-table-column prop="symbol" label="代码" width="104"/><el-table-column prop="signal_type" label="信号" width="85"/><el-table-column prop="horizon_key" label="期限" width="70"/><el-table-column label="触发时间" width="160"><template #default="{ row }">{{ dateText(row.observed_at) }}</template></el-table-column><el-table-column label="状态" width="96"><template #default="{ row }"><el-tag :type="outcomeStatusType(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="方向收益" width="115"><template #default="{ row }">{{ outcomePercent(row.raw_return) }}</template></el-table-column><el-table-column label="MFE / MAE" width="150"><template #default="{ row }">{{ outcomePercent(row.maximum_favorable_excursion) }} / {{ outcomePercent(row.maximum_adverse_excursion) }}</template></el-table-column><el-table-column prop="tradability" label="测量方式" min-width="150" show-overflow-tooltip/></el-table>
  </el-card>
  <el-card shadow="never"><template #header><div class="card-header"><span>分析师成绩单门禁</span><el-button :loading="actionLoading === '刷新分析师成绩单'" @click="recomputeAnalystScorecards">刷新成绩单</el-button></div></template>
    <el-alert title="分析师文本不会因篇数多而获得更高权重。只有方向明确、标的可映射且未来路径已结算的股票观点，才可累积成绩单。" type="warning" :closable="false" show-icon/>
    <el-table :data="analystReadiness" max-height="260" size="small" class="section-gap"><el-table-column prop="name" label="分析师" min-width="110"/><el-table-column prop="stock_claims" label="股票观点" width="95"/><el-table-column prop="directional_stock_claims" label="方向明确" width="95"/><el-table-column prop="settled_stock_outcomes" label="已结算" width="90"/><el-table-column label="可入权重" width="90"><template #default="{ row }"><el-tag :type="row.mature ? 'success' : 'warning'">{{ row.mature ? '可复核' : '未成熟' }}</el-tag></template></el-table-column><el-table-column label="门禁原因" min-width="210"><template #default="{ row }">{{ analystReadinessText(row.reason) }}</template></el-table-column></el-table>
    <el-table v-if="analystScorecards.length" :data="analystScorecards" max-height="240" size="small"><el-table-column prop="analyst_id" label="分析师"/><el-table-column prop="horizon_days" label="周期" width="75"/><el-table-column prop="observations" label="样本" width="80"/><el-table-column label="命中率" width="95"><template #default="{ row }">{{ outcomePercent(row.hit_rate) }}</template></el-table-column><el-table-column label="方向收益" width="115"><template #default="{ row }">{{ outcomePercent(row.mean_directional_return) }}</template></el-table-column><el-table-column label="超额收益" width="115"><template #default="{ row }">{{ outcomePercent(row.mean_excess_return) }}</template></el-table-column></el-table>
  </el-card>
  <el-card shadow="never" header="龙虎榜：下一交易日观察背景"><el-alert title="仅展示已入库的龙虎榜事件；用于复盘“谁在何处出现异常交易”，不倒灌为当日盘中信号。" type="warning" :closable="false" show-icon/><el-table :data="lhbEvents" max-height="360" size="small" class="section-gap"><el-table-column prop="symbol" label="代码" width="105"/><el-table-column prop="occurred_at" label="披露时间" width="165"><template #default="{ row }">{{ dateText(row.occurred_at) }}</template></el-table-column><el-table-column prop="title" label="龙虎榜事件" min-width="330" show-overflow-tooltip/><el-table-column prop="source" label="来源" width="110"/><el-table-column label="原始公告" width="88"><template #default="{ row }"><el-link v-if="row.url" :href="row.url" target="_blank" type="primary">查看</el-link><span v-else>-</span></template></el-table-column></el-table></el-card>

</template>
