<script lang="ts">
import { defineComponent, inject } from 'vue';
import { Refresh, WarningFilled } from '@element-plus/icons-vue';
import VChart from 'vue-echarts';
import { dashboardContextKey } from '../../dashboard-context';

export default defineComponent({
  name: 'MarketSnapshotsTab',
  components: { Refresh, VChart, WarningFilled },
  setup() {
    const dashboard = inject(dashboardContextKey);
    if (!dashboard) throw new Error('research tab requires the dashboard shell context');
    return dashboard as Record<string, any>;
  },
});
</script>

<template>

  <el-alert title="午盘与收盘快照默认不调用公开全市场报价；启用前须确认上游限频。公开报价仅用于市场补充，未经授权的实时分钟源不会进入推荐决策。" type="warning" :closable="false" show-icon />
  <el-row :gutter="14" class="section-gap">
    <el-col :md="8" :xs="24"><el-card shadow="never" header="全市场基准"><el-statistic title="已登记A股" :value="count('all_a_symbols')"/><el-text type="info">每日盘前从 stock_basic 刷新。</el-text><div class="card-actions"><el-button type="primary" :loading="actionLoading === '刷新全市场股票池'" @click="syncAllMarketUniverse">刷新股票池</el-button></div></el-card></el-col>
    <el-col :md="8" :xs="24"><el-card shadow="never" header="盘中补充"><el-statistic title="市场快照次数" :value="count('market_snapshot_runs')"/><el-text type="info">上海时间 11:35 自动运行。</el-text><div class="card-actions"><el-button :loading="actionLoading === '生成午盘全市场快照'" @click="runMarketSnapshot('midday')">生成午盘快照</el-button></div></el-card></el-col>
    <el-col :md="8" :xs="24"><el-card shadow="never" header="收盘确认"><template v-if="overview.latest_market_snapshot"><el-descriptions :column="1" border size="small"><el-descriptions-item label="状态"><el-tag :type="snapshotType(overview.latest_market_snapshot.status)">{{ overview.latest_market_snapshot.status }}</el-tag></el-descriptions-item><el-descriptions-item label="覆盖率">{{ Math.round(overview.latest_market_snapshot.coverage * 10000) / 100 }}%</el-descriptions-item><el-descriptions-item label="决策可用">{{ overview.latest_market_snapshot.decision_eligible ? '是' : '否' }}</el-descriptions-item></el-descriptions></template><el-empty v-else description="尚无市场快照" :image-size="56"/><div class="card-actions"><el-button :loading="actionLoading === '生成收盘全市场快照'" @click="runMarketSnapshot('close')">生成收盘快照</el-button><el-button type="primary" :loading="actionLoading === '同步全市场收盘日线'" @click="syncFullMarketDaily">同步日线</el-button></div></el-card></el-col>
  </el-row>
  <el-row :gutter="14">
    <el-col :md="8" :xs="24"><el-card shadow="never" header="同花顺板块目录"><el-statistic title="已登记板块" :value="count('sectors')"/><el-text type="info">目录来自 Fuyao 同花顺指数列表（fuyao_ths_concept），保留分类类型和来源。</el-text><div class="card-actions"><el-button :loading="actionLoading === '同步同花顺板块目录'" @click="syncSectorDirectory">同步目录</el-button></div></el-card></el-col>
    <el-col :md="8" :xs="24"><el-card shadow="never" header="板块成分批次"><el-statistic title="活跃成分关系" :value="count('active_sector_memberships')"/><el-form inline class="section-gap"><el-form-item label="起点"><el-input-number v-model="sectorMemberOffset" :min="0" :step="sectorMemberLimit" controls-position="right"/></el-form-item><el-form-item label="数量"><el-input-number v-model="sectorMemberLimit" :min="1" :max="50" controls-position="right"/></el-form-item></el-form><div class="card-actions"><el-button :loading="actionLoading === '同步板块成分批次'" @click="syncSectorMembers">同步成分</el-button></div></el-card></el-col>
    <el-col :md="8" :xs="24"><el-card shadow="never" header="行业资金流"><el-statistic title="行业观测记录" :value="count('sector_market_observations')"/><el-date-picker v-model="sectorFlowDate" type="date" value-format="YYYY-MM-DD" class="section-gap"/><div class="card-actions"><el-button type="primary" :loading="actionLoading === '同步同花顺行业资金流'" @click="syncSectorFlows">同步资金流</el-button></div></el-card></el-col>
  </el-row>
  <el-card shadow="never" class="section-gap"><template #header><div class="card-header"><span>概念资金流与涨停候选</span><el-space><el-button :loading="actionLoading === '同步概念资金流与涨停强度'" @click="syncConceptSignals">同步概念信号</el-button><el-button :loading="actionLoading === '生成概念涨停候选'" @click="syncConceptCandidates">生成涨停候选</el-button><el-button :loading="actionLoading === '同步巨潮公告'" @click="syncCninfoAnnouncements">同步公告</el-button><el-button type="primary" :loading="actionLoading === '板块到个股一键研究'" @click="runBoardResearch">一键研究</el-button></el-space></div></template><el-alert title="候选仅由同日同花顺概念成分代码与同花顺涨停池代码精确相交得到；板块扫描不直接构成交易建议。" type="info" :closable="false" show-icon/><el-table :data="conceptSignals.slice(0, 20)" max-height="320" size="small" class="section-gap"><el-table-column prop="label" label="概念" min-width="130"/><el-table-column prop="net_amount" label="净流入" width="105"/><el-table-column label="涨跌幅" width="90"><template #default="{ row }">{{ displayValue(row.change_pct) }}%</template></el-table-column><el-table-column prop="leading_label" label="板块领涨" width="110"/><el-table-column prop="up_nums" label="涨停数" width="78"/><el-table-column prop="aggregate_score" label="扫描分" width="82"/><el-table-column label="证据" width="120"><template #default="{ row }"><el-tag size="small" type="info">{{ row.provider_key }}</el-tag></template></el-table-column></el-table><el-table :data="conceptCandidates" max-height="360" size="small" class="section-gap"><el-table-column prop="concept_label" label="高流入概念" min-width="135"/><el-table-column prop="board_net_amount" label="板块净流入" width="115"/><el-table-column prop="symbol" label="代码" width="105"/><el-table-column prop="name" label="涨停股" min-width="100"/><el-table-column prop="limit_tag" label="连板" width="85"/><el-table-column label="成分" width="86"><template #default="{ row }"><el-tag size="small" :type="row.membership_status === 'completed' || row.membership_status === 'unchanged' ? 'success' : 'warning'">{{ row.membership_status === 'completed' || row.membership_status === 'unchanged' ? '完整' : '截断' }}</el-tag></template></el-table-column><el-table-column label="涨幅" width="78"><template #default="{ row }">{{ displayValue(row.pct_change) }}%</template></el-table-column><el-table-column prop="limit_amount" label="封单额" width="105"/><el-table-column prop="description" label="涨停原因" min-width="210" show-overflow-tooltip/><el-table-column label="研究" width="88" fixed="right"><template #default="{ row }"><el-button link type="primary" @click="studyConceptCandidate(row.symbol)">技术分析</el-button></template></el-table-column></el-table></el-card>
  <el-card shadow="never" header="官方公告事件"><el-table :data="announcements" max-height="320" size="small"><el-table-column prop="symbol" label="代码" width="105"/><el-table-column prop="event_type" label="类型" width="130"/><el-table-column prop="occurred_at" label="披露时间" width="165"><template #default="{ row }">{{ dateText(row.occurred_at) }}</template></el-table-column><el-table-column prop="title" label="标题" min-width="280" show-overflow-tooltip/><el-table-column prop="source" label="来源" width="110"/><el-table-column label="文件" width="80"><template #default="{ row }"><el-link v-if="row.url" :href="row.url" target="_blank" type="primary">PDF</el-link><span v-else>-</span></template></el-table-column></el-table></el-card>
  <el-card shadow="never" header="行业资金流（开盘啦，同花顺行业口径）"><el-table :data="sectorFlows" max-height="360"><el-table-column prop="trading_date" label="交易日" width="105"/><el-table-column prop="label" label="行业" min-width="130"/><el-table-column prop="change_pct" label="涨跌幅" width="100"><template #default="{ row }">{{ displayValue(row.change_pct) }}%</template></el-table-column><el-table-column label="净流入" width="115"><template #default="{ row }">{{ row.net_amount === null || row.net_amount === undefined ? '-' : `${(Number(row.net_amount) / (row.taxonomy_key === 'longhu_ths_industry' ? 1e8 : 1)).toFixed(2)}亿` }}</template></el-table-column><el-table-column prop="net_buy_amount" label="买入额" width="115"/><el-table-column prop="net_sell_amount" label="卖出额" width="115"/><el-table-column prop="leading_label" label="领涨股" width="115"/><el-table-column prop="constituent_count" label="公司数" width="85"/><el-table-column prop="provider_key" label="来源" width="130"/></el-table></el-card>
  <el-card shadow="never" header="同花顺板块目录"><el-table :data="sectors" max-height="320" size="small"><el-table-column prop="sector_key" label="板块代码" width="130"/><el-table-column prop="label" label="板块名称" min-width="200"/><el-table-column prop="active_members" label="已同步成分" width="110"/><el-table-column prop="updated_at" label="更新于" min-width="165"><template #default="{ row }">{{ dateText(row.updated_at) }}</template></el-table-column></el-table></el-card>
  <el-card shadow="never" header="午盘与收盘市场情况"><el-table :data="marketSnapshots" max-height="360"><el-table-column prop="exchange_date" label="交易日" width="110"/><el-table-column prop="session" label="时点" width="90"/><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="snapshotType(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column label="覆盖" width="110"><template #default="{ row }">{{ row.quote_count }} / {{ row.universe_count }}</template></el-table-column><el-table-column label="上涨 / 下跌" width="140"><template #default="{ row }">{{ displayValue(row.summary?.advancers) }} / {{ displayValue(row.summary?.decliners) }}</template></el-table-column><el-table-column label="中位涨跌" width="110"><template #default="{ row }">{{ displayValue(row.summary?.median_change_pct) }}%</template></el-table-column><el-table-column label="成交额" width="140"><template #default="{ row }">{{ displayValue(row.summary?.market_amount) }}</template></el-table-column><el-table-column label="决策" width="85"><template #default="{ row }"><el-tag :type="row.decision_eligible ? 'success' : 'info'">{{ row.decision_eligible ? '可用' : '补充' }}</el-tag></template></el-table-column><el-table-column label="质量标记" min-width="260"><template #default="{ row }"><el-space wrap><el-tag v-for="flag in row.quality_flags ?? []" :key="flag" size="small" type="warning">{{ flag }}</el-tag></el-space></template></el-table-column></el-table></el-card>
  <el-card shadow="never" header="接口能力事实"><el-table :data="providerApiCapabilities" max-height="320" size="small"><el-table-column prop="label" label="来源"/><el-table-column prop="api_name" label="API"/><el-table-column prop="availability" label="状态" width="110"><template #default="{ row }"><el-tag :type="row.availability === 'verified' ? 'success' : row.availability === 'unsupported' || row.availability === 'failed' ? 'danger' : 'warning'">{{ row.availability }}</el-tag></template></el-table-column><el-table-column prop="frequency" label="频率" width="150"/><el-table-column label="决策" width="90"><template #default="{ row }">{{ row.decision_eligible ? '可参与' : '仅证据' }}</template></el-table-column><el-table-column prop="note" label="审计说明" show-overflow-tooltip/></el-table></el-card>

</template>
