<script lang="ts">
import { defineComponent, inject } from 'vue';
import { Refresh, WarningFilled } from '@element-plus/icons-vue';
import VChart from 'vue-echarts';
import { dashboardContextKey } from '../../dashboard-context';
import RealtimeServicesPanel from '../../components/RealtimeServicesPanel.vue';

export default defineComponent({
  name: 'ProviderTab',
  components: { Refresh, RealtimeServicesPanel, VChart, WarningFilled },
  setup() {
    const dashboard = inject(dashboardContextKey);
    if (!dashboard) throw new Error('research tab requires the dashboard shell context');
    return dashboard as Record<string, any>;
  },
});
</script>

<template>

  <RealtimeServicesPanel :services="realtimeServices" :adapter-health="adapterHealth" :runtime-health="runtimeHealth" :loading="realtimeLoading" :error="realtimeError" :date-text="dateText" :age-text="ageText" :bytes-text="bytesText" :state-type="realtimeStateType" :state-text="realtimeStateText" :delivery-detail="realtimeDeliveryDetail" @refresh="loadRealtimeServices" />
  <el-card shadow="never" header="外部数据源"><el-table :data="catalog.providers ?? []"><el-table-column prop="label" label="来源" min-width="170"/><el-table-column prop="provider_key" label="Provider key" min-width="160"/><el-table-column prop="protocol" label="协议" width="120"/><el-table-column label="限频" width="128"><template #default="{ row }">{{ row.rate_limit_per_minute ? `${row.rate_limit_per_minute}/分` : '-' }}{{ row.min_interval_seconds ? ` · ≥${row.min_interval_seconds}秒` : '' }}</template></el-table-column><el-table-column label="实时覆盖" min-width="170"><template #default="{ row }"><el-tag size="small" :type="row.realtime_coverage === 'verified_partial' ? 'success' : row.realtime_coverage === 'unavailable' ? 'danger' : 'info'">{{ row.realtime_coverage === 'verified_partial' ? `已实测 ${row.realtime_apis?.length ?? 0} 项` : row.realtime_coverage === 'unavailable' ? '明确不可用' : row.realtime_coverage ?? '-' }}</el-tag><small class="catalog-check-time">{{ row.realtime_note ?? '' }}</small></template></el-table-column><el-table-column label="Super 路由首选" min-width="190"><template #default="{ row }"><span v-if="row.name === 'super_sdk' || row.name === 'super_get'">{{ row.super_alias_first_apis?.length ?? 0 }} 项</span><span v-else>-</span><small v-if="row.super_alias_first_apis?.length" class="catalog-check-time">{{ row.super_alias_first_apis.join(', ') }}</small></template></el-table-column><el-table-column label="完整性边界" min-width="210"><template #default="{ row }"><span v-if="row.name === 'super_get'">完整 {{ row.complete_query_apis?.length ?? 0 }} 项；受限 {{ row.bounded_only_apis?.join(', ') || '无' }}；需对账 {{ row.reconciliation_required_apis?.join(', ') || '无' }}</span><span v-else>{{ row.name === 'super_sdk' ? '广域成员/事件完整源' : row.name === 'primary' ? '全A名录基准；无实时能力' : '-' }}</span></template></el-table-column><el-table-column label="配置" width="100"><template #default="{ row }"><el-tag :type="row.configured ? 'success' : 'info'">{{ row.configured ? '已配置' : '未配置' }}</el-tag></template></el-table-column></el-table></el-card>
  <el-card shadow="never" header="能力健康"><el-table :data="providerHealth" max-height="500"><el-table-column prop="label" label="来源"/><el-table-column prop="capability" label="能力"/><el-table-column label="状态" width="110"><template #default="{ row }"><el-tag :type="healthState(row)">{{ row.circuit_open_until ? '已熔断' : row.last_error ? '异常' : row.last_success_at ? '正常' : '未运行' }}</el-tag></template></el-table-column><el-table-column label="最近成功" width="175"><template #default="{ row }">{{ dateText(row.last_success_at) }}</template></el-table-column><el-table-column prop="last_latency_ms" label="延迟 ms" width="100"/><el-table-column prop="last_row_count" label="行数" width="80"/><el-table-column prop="last_error" label="最近错误" show-overflow-tooltip/></el-table></el-card>
  <el-card shadow="never" header="研究存储水位" class="section-gap"><el-alert :title="runtimeHealth.resources?.research_storage?.state === 'stop_nonessential_high_frequency' ? '已达停止水位：系统仅暂停可选高频原始证据，观察池报价、风险提醒与结算继续运行。' : runtimeHealth.resources?.research_storage?.state === 'warning' ? '接近研究存储预算：请关注数据库与 artifact 增长。' : '存储预算健康：高频证据仍按保留期采集和清理。'" :type="runtimeHealth.resources?.research_storage?.state === 'healthy' ? 'success' : 'warning'" :closable="false" show-icon/><el-descriptions :column="mobileLayout ? 1 : 3" border size="small" class="section-gap"><el-descriptions-item label="量化热库">{{ bytesText(runtimeHealth.resources?.research_storage?.hot_database?.used_bytes) }} / {{ bytesText(runtimeHealth.resources?.research_storage?.hot_database?.budget_bytes) }}</el-descriptions-item><el-descriptions-item label="受管研究空间">{{ bytesText(runtimeHealth.resources?.research_storage?.managed?.used_bytes) }} / {{ bytesText(runtimeHealth.resources?.research_storage?.managed?.budget_bytes) }}</el-descriptions-item><el-descriptions-item label="可选高频采集">{{ runtimeHealth.resources?.research_storage?.allow_nonessential_high_frequency === false ? '已暂停' : '允许' }}</el-descriptions-item></el-descriptions></el-card>
  <el-card shadow="never" header="边缘 raw 溢出归档" class="section-gap"><el-alert :title="runtimeHealth.runtime_tasks?.raw_overflow_archive?.enabled ? `状态：${runtimeHealth.runtime_tasks.raw_overflow_archive.state ?? 'unknown'}；百度仅作冷存储` : '未启用（演练完成后再开启）'" :type="runtimeHealth.runtime_tasks?.raw_overflow_archive?.enabled ? (runtimeHealth.runtime_tasks.raw_overflow_archive.state === 'critical' ? 'error' : 'warning') : 'info'" :closable="false" show-icon/><el-descriptions :column="mobileLayout ? 1 : 4" border size="small" class="section-gap"><el-descriptions-item label="队列">{{ runtimeHealth.runtime_tasks?.raw_overflow_archive?.queue?.queue_depth ?? 0 }} 批</el-descriptions-item><el-descriptions-item label="已校验">{{ runtimeHealth.runtime_tasks?.raw_overflow_archive?.queue?.verified ?? 0 }} 批</el-descriptions-item><el-descriptions-item label="游标流">{{ runtimeHealth.runtime_tasks?.raw_overflow_archive?.offsets?.length ?? 0 }} 条</el-descriptions-item><el-descriptions-item label="热窗口">{{ runtimeHealth.runtime_tasks?.raw_overflow_archive?.hot_window_hours ?? 24 }} 小时</el-descriptions-item></el-descriptions></el-card>
  <el-card shadow="never" class="section-gap" header="纸面策略账本">
    <el-alert title="只记录已确认信号的研究提案；不连接券商、不自动委托。T+1、100股整手、停牌/涨跌停与费用滑点门禁均在纸面层执行。" type="info" :closable="false" show-icon/>
    <el-descriptions :column="mobileLayout ? 1 : 4" border size="small" class="section-gap"><el-descriptions-item label="模式">{{ paperStatus.mode ?? '未读取' }}</el-descriptions-item><el-descriptions-item label="真实订单">{{ paperStatus.live_orders ? '启用' : '关闭' }}</el-descriptions-item><el-descriptions-item label="研究提案">{{ paperStatus.decisions?.length ?? 0 }}</el-descriptions-item><el-descriptions-item label="持仓记录">{{ paperStatus.positions?.length ?? 0 }}</el-descriptions-item></el-descriptions>
    <el-descriptions v-if="paperStatus.latest_portfolio" :column="mobileLayout ? 1 : 4" border size="small" class="section-gap"><el-descriptions-item label="组合净值">{{ paperStatus.latest_portfolio.equity ?? '-' }}</el-descriptions-item><el-descriptions-item label="总暴露">{{ paperStatus.latest_portfolio.gross_exposure ?? '-' }}</el-descriptions-item><el-descriptions-item label="净暴露">{{ paperStatus.latest_portfolio.net_exposure ?? '-' }}</el-descriptions-item><el-descriptions-item label="回撤">{{ paperStatus.latest_portfolio.drawdown ?? '-' }}</el-descriptions-item></el-descriptions>
    <el-table v-if="paperSectorExposureItems().length" :data="paperSectorExposureItems()" size="small" max-height="220" class="section-gap"><el-table-column prop="sector" label="板块暴露" min-width="220"/><el-table-column label="占比" width="120"><template #default="{ row }">{{ (row.value * 100).toFixed(2) }}%</template></el-table-column></el-table>
    <el-table :data="paperStatus.decisions ?? []" max-height="240" size="small"><el-table-column prop="decision_at" label="决策时间" width="165"><template #default="{ row }">{{ chinaDateTime(row.decision_at) }}</template></el-table-column><el-table-column prop="symbol" label="标的" width="100"/><el-table-column prop="strategy_key" label="策略" min-width="190"/><el-table-column prop="status" label="状态" width="90"/><el-table-column label="风险" min-width="250"><template #default="{ row }">{{ (row.risk_flags ?? []).join('、') || '-' }}</template></el-table-column></el-table>
    <el-table v-if="paperStatus.risk_events?.length" :data="paperStatus.risk_events" max-height="220" size="small" class="section-gap"><el-table-column prop="occurred_at" label="时间" width="165"><template #default="{ row }">{{ chinaDateTime(row.occurred_at) }}</template></el-table-column><el-table-column prop="symbol" label="标的" width="100"/><el-table-column prop="event_type" label="事件" width="180"/><el-table-column prop="severity" label="级别" width="85"/><el-table-column prop="message" label="说明" show-overflow-tooltip/></el-table>
    <el-divider content-position="left">策略决策漏斗（最近一日）</el-divider>
    <el-descriptions :column="mobileLayout ? 1 : 6" border size="small"><el-descriptions-item label="报价证据">{{ strategyFunnel.funnel?.quote_observations ?? 0 }}</el-descriptions-item><el-descriptions-item label="信号事件">{{ strategyFunnel.funnel?.signal_events ?? 0 }}</el-descriptions-item><el-descriptions-item label="独立 episode">{{ strategyFunnel.funnel?.episodes ?? 0 }}</el-descriptions-item><el-descriptions-item label="活跃 episode">{{ strategyFunnel.funnel?.active_episodes ?? 0 }}</el-descriptions-item><el-descriptions-item label="纸面提案">{{ strategyFunnel.funnel?.paper_proposals ?? 0 }}</el-descriptions-item><el-descriptions-item label="风险阻断">{{ strategyFunnel.funnel?.blocked_proposals ?? 0 }}</el-descriptions-item></el-descriptions>
    <el-divider content-position="left">事件回放与概率校准门禁</el-divider>
    <el-alert :title="`回放 ${strategyGovernance.replay_runs?.length ?? 0} 次｜校准 ${strategyGovernance.probability_calibrations?.length ?? 0} 次。${strategyGovernance.promotion_boundary ?? '未通过回放和人工批准前保持研究模式。'}`" type="warning" :closable="false" show-icon/>
    <el-table :data="strategyGovernance.replay_runs ?? []" max-height="160" size="small" class="section-gap"><el-table-column prop="created_at" label="回放时间" width="165"><template #default="{ row }">{{ chinaDateTime(String(row.created_at ?? '')) }}</template></el-table-column><el-table-column prop="strategy_key" label="策略" min-width="180"/><el-table-column prop="status" label="状态" width="100"/><el-table-column prop="trace_hash" label="可复算哈希" min-width="200" show-overflow-tooltip/></el-table>
    <el-table :data="strategyGovernance.probability_calibrations ?? []" max-height="160" size="small" class="section-gap"><el-table-column prop="strategy_family" label="策略族" min-width="160"/><el-table-column prop="signal_type" label="动作" width="90"/><el-table-column prop="horizon_key" label="期限" width="90"/><el-table-column prop="status" label="校准状态" min-width="150"/><el-table-column prop="created_at" label="生成时间" width="165"><template #default="{ row }">{{ chinaDateTime(String(row.created_at ?? '')) }}</template></el-table-column></el-table>
  </el-card>

</template>
