<script lang="ts">
import { defineComponent, inject } from 'vue';
import { Refresh, WarningFilled } from '@element-plus/icons-vue';
import VChart from 'vue-echarts';
import { dashboardContextKey } from '../../dashboard-context';

export default defineComponent({
  name: 'StockStudyTab',
  components: { Refresh, VChart, WarningFilled },
  setup() {
    const dashboard = inject(dashboardContextKey);
    if (!dashboard) throw new Error('research tab requires the dashboard shell context');
    return dashboard as Record<string, any>;
  },
});
</script>

<template>

  <el-card shadow="never" header="股票研究">
    <el-form inline class="study-form" @submit.prevent="runStockStudy">
      <el-form-item label="股票代码"><el-input v-model="studySymbol" placeholder="000636.SZ" clearable /></el-form-item>
      <el-form-item label="日线窗口"><el-input-number v-model="studyLookback" :min="5" :max="45" /></el-form-item>
      <el-form-item><el-space><el-button type="primary" :loading="studyLoading" @click="runStockStudy">刷新数据并分析</el-button><el-button :loading="actionLoading === 'AkShare补充探测'" @click="probeAkshareSupplement">AkShare完整补充</el-button><el-button :loading="actionLoading === 'AkShare宏观跨资产补充'" @click="probeAkshareMacroSupplement">宏观跨资产</el-button></el-space></el-form-item>
    </el-form>
    <el-alert v-if="studyError" :title="studyError" type="error" :closable="false" show-icon />
  </el-card>
  <template v-if="stockStudy">
    <el-alert :title="stockStudy.combined.notice" type="info" :closable="false" show-icon class="section-gap" />
    <el-row :gutter="14">
      <el-col :md="12" :xs="24"><el-card shadow="never" header="综合研究"><el-descriptions :column="1" border><el-descriptions-item label="标的">{{ stockStudy.symbol }}</el-descriptions-item><el-descriptions-item label="截至">{{ stockStudy.as_of_date }}</el-descriptions-item><el-descriptions-item label="综合评分"><el-progress :percentage="stockStudy.combined.score" :stroke-width="12" /></el-descriptions-item><el-descriptions-item label="结论"><el-tag :type="studyType(stockStudy.combined.stance)">{{ studyStance(stockStudy.combined.stance) }}</el-tag></el-descriptions-item></el-descriptions><el-divider content-position="left">依据</el-divider><el-space wrap><el-tag v-for="reason in stockStudy.combined.reasons" :key="reason" type="info">{{ reason }}</el-tag></el-space></el-card></el-col>
      <el-col :md="12" :xs="24"><el-card shadow="never" header="技术面"><el-descriptions :column="2" border><el-descriptions-item label="趋势"><el-tag :type="stockStudy.technical.trend === 'positive' ? 'success' : stockStudy.technical.trend === 'negative' ? 'danger' : 'info'">{{ stockStudy.technical.trend }}</el-tag></el-descriptions-item><el-descriptions-item label="评分">{{ displayValue(stockStudy.technical.score) }}</el-descriptions-item><el-descriptions-item label="收盘">{{ displayValue(stockStudy.technical.close) }}</el-descriptions-item><el-descriptions-item label="5日涨跌">{{ displayValue(stockStudy.technical.return_5d_pct) }}%</el-descriptions-item><el-descriptions-item label="SMA 5">{{ displayValue(stockStudy.technical.sma_5) }}</el-descriptions-item><el-descriptions-item label="SMA 20">{{ displayValue(stockStudy.technical.sma_20) }}</el-descriptions-item><el-descriptions-item label="RSI 14">{{ displayValue(stockStudy.technical.rsi_14) }}</el-descriptions-item><el-descriptions-item label="数据日期">{{ displayValue(stockStudy.technical.as_of_date) }}</el-descriptions-item></el-descriptions></el-card></el-col>
    </el-row>
    <el-card shadow="never" header="按需补齐状态">
      <el-alert :title="stockStudy.on_demand_readiness?.decision_ready ? '该股票近窗口 P0 数据已补齐，可以进入单票研究。' : `仍缺 P0：${stockStudy.on_demand_readiness?.blockers.join(', ') || '-'}`" :type="stockStudy.on_demand_readiness?.decision_ready ? 'success' : 'warning'" :closable="false" show-icon />
      <el-table :data="stockStudy.on_demand_readiness?.items ?? []" size="small" max-height="260" class="section-gap">
        <el-table-column prop="label" label="数据" min-width="140"/>
        <el-table-column prop="api_name" label="API" width="130"/>
        <el-table-column prop="priority" label="优先级" width="80"/>
        <el-table-column label="状态" width="90"><template #default="{ row }"><el-tag :type="featureStatusType(row.status)">{{ row.status }}</el-tag></template></el-table-column>
        <el-table-column prop="rows" label="窗口行数" width="100"/>
        <el-table-column prop="latest_date" label="最新日期" width="120"/>
      </el-table>
    </el-card>
    <el-row :gutter="14">
      <el-col :md="12" :xs="24"><el-card shadow="never" header="公司与实时数据"><el-descriptions :column="2" border><el-descriptions-item v-for="(value, key) in studyMarketRecord('profile')" :key="String(key)" :label="String(key)">{{ displayValue(value) }}</el-descriptions-item></el-descriptions><el-divider content-position="left">主源与超级源实时分钟（仅交易时段）</el-divider><el-descriptions :column="2" border><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_realtime')" :key="String(key)">{{ displayValue(value) }}</el-descriptions-item></el-descriptions><el-divider content-position="left">东方财富公开报价</el-divider><el-descriptions :column="2" border><el-descriptions-item v-for="(value, key) in studyMarketRecord('eastmoney_quote')" :key="`east-${String(key)}`" :label="String(key)">{{ displayValue(value) }}</el-descriptions-item></el-descriptions><el-divider content-position="left">新浪财经公开报价</el-divider><el-descriptions :column="2" border><el-descriptions-item v-for="(value, key) in studyMarketRecord('sina_quote')" :key="`sina-${String(key)}`" :label="String(key)">{{ displayValue(value) }}</el-descriptions-item></el-descriptions></el-card></el-col>
      <el-col :md="12" :xs="24"><el-card shadow="never" header="估值、交易约束、资金与筹码"><el-descriptions :column="2" border><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_daily_basic')" :key="`basic-${String(key)}`" :label="`估值 ${String(key)}`">{{ displayValue(value) }}</el-descriptions-item><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_limit')" :key="`limit-${String(key)}`" :label="`涨跌停 ${String(key)}`">{{ displayValue(value) }}</el-descriptions-item><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_adj_factor')" :key="`adj-${String(key)}`" :label="`复权 ${String(key)}`">{{ displayValue(value) }}</el-descriptions-item><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_moneyflow')" :key="`flow-${String(key)}`" :label="`资金 ${String(key)}`">{{ displayValue(value) }}</el-descriptions-item><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_ths_moneyflow')" :key="`ths-${String(key)}`" :label="`同花顺 ${String(key)}`">{{ displayValue(value) }}</el-descriptions-item><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_chip')" :key="`chip-${String(key)}`" :label="`筹码 ${String(key)}`">{{ displayValue(value) }}</el-descriptions-item><el-descriptions-item v-for="(value, key) in studyMarketRecord('latest_chip_distribution')" :key="`chips-${String(key)}`" :label="`筹码分布 ${String(key)}`">{{ displayValue(value) }}</el-descriptions-item></el-descriptions></el-card></el-col>
    </el-row>
    <el-card shadow="never" header="东财主力与散户资金"><el-descriptions :column="3" border><el-descriptions-item label="交易日">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').trade_date) }}</el-descriptions-item><el-descriptions-item label="主力净流入">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').net_amount) }}</el-descriptions-item><el-descriptions-item label="主力占比">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').net_amount_rate) }}</el-descriptions-item><el-descriptions-item label="超大单净额">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').buy_elg_amount) }}</el-descriptions-item><el-descriptions-item label="超大单占比">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').buy_elg_amount_rate) }}</el-descriptions-item><el-descriptions-item label="大单净额">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').buy_lg_amount) }}</el-descriptions-item><el-descriptions-item label="大单占比">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').buy_lg_amount_rate) }}</el-descriptions-item><el-descriptions-item label="中单净额">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').buy_md_amount) }}</el-descriptions-item><el-descriptions-item label="小单净额">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').buy_sm_amount) }}</el-descriptions-item><el-descriptions-item label="小单占比">{{ displayValue(studyMarketRecord('latest_dc_moneyflow').buy_sm_amount_rate) }}</el-descriptions-item></el-descriptions></el-card>
    <el-card shadow="never" header="官方公告事件"><el-table :data="stockStudy.events?.announcements ?? []" size="small" max-height="260"><el-table-column prop="event_type" label="类型" width="130"/><el-table-column prop="occurred_at" label="披露时间" width="165"><template #default="{ row }">{{ dateText(row.occurred_at) }}</template></el-table-column><el-table-column prop="title" label="标题" min-width="260" show-overflow-tooltip/><el-table-column label="文件" width="78"><template #default="{ row }"><el-link v-if="row.url" :href="row.url" target="_blank" type="primary">PDF</el-link><span v-else>-</span></template></el-table-column></el-table></el-card>
    <el-card shadow="never" header="数据源执行结果"><el-table :data="stockStudy.sources" size="small"><el-table-column prop="source" label="输入" min-width="150"/><el-table-column prop="provider" label="实际来源" min-width="130"/><el-table-column prop="api_name" label="接口" width="140"/><el-table-column label="状态" width="100"><template #default="{ row }"><el-tag :type="sourceType(row.status)">{{ row.status }}</el-tag></template></el-table-column><el-table-column prop="received" label="响应" width="80"/><el-table-column prop="stored" label="证据" width="80"/><el-table-column prop="error" label="错误" show-overflow-tooltip/></el-table></el-card>
    <el-row :gutter="14"><el-col :md="14" :xs="24"><el-card shadow="never" header="最近日线"><el-table :data="studyBars" max-height="400" size="small"><el-table-column label="日期" width="115"><template #default="{ row }">{{ displayValue(row.trade_date) }}</template></el-table-column><el-table-column label="开盘"><template #default="{ row }">{{ displayValue(row.open) }}</template></el-table-column><el-table-column label="最高"><template #default="{ row }">{{ displayValue(row.high) }}</template></el-table-column><el-table-column label="最低"><template #default="{ row }">{{ displayValue(row.low) }}</template></el-table-column><el-table-column label="收盘"><template #default="{ row }">{{ displayValue(row.close) }}</template></el-table-column><el-table-column label="成交量"><template #default="{ row }">{{ displayValue(row.vol) }}</template></el-table-column></el-table></el-card></el-col><el-col :md="10" :xs="24"><el-card shadow="never" header="远端分析师证据"><el-descriptions :column="2" border><el-descriptions-item label="观点数">{{ displayValue(stockStudy.analyst.summary.claim_count) }}</el-descriptions-item><el-descriptions-item label="聚合方向">{{ displayValue(stockStudy.analyst.summary.direction) }}</el-descriptions-item><el-descriptions-item label="加权分">{{ displayValue(stockStudy.analyst.summary.score) }}</el-descriptions-item><el-descriptions-item label="偏多/偏空">{{ displayValue(stockStudy.analyst.summary.positive) }} / {{ displayValue(stockStudy.analyst.summary.negative) }}</el-descriptions-item></el-descriptions><el-table :data="stockStudy.analyst.claims" max-height="270" size="small" class="section-gap"><el-table-column prop="analyst_name" label="分析师"/><el-table-column label="方向" width="70"><template #default="{ row }"><el-tag :type="row.direction > 0 ? 'success' : row.direction < 0 ? 'danger' : 'info'">{{ claimDirection(row.direction) }}</el-tag></template></el-table-column><el-table-column prop="evidence" label="证据" show-overflow-tooltip/></el-table></el-card></el-col></el-row>
  </template>
  <el-empty v-else-if="!studyLoading" description="输入股票代码后开始研究" :image-size="80" />

</template>
