#!/usr/bin/env python3
"""Generate workflows/CATALOG.md: every n8n workflow, where it runs, how it ships.

Seventeen workflows run on two n8n instances (the workstation compose stack and
the 47edge relay stack), and their sources live in three shapes: the exported
``workflows/managed/`` mirror of the workstation instance, authored top-level
JSON files, and the per-component edge files.  Answering "what exists, when
does it fire, which component owns it, how do I release it" meant reading all
of them.  This generator renders one table per instance; ``--check`` fails
when the committed catalog is stale, so a workflow change arrives with its
catalog row.
"""

from __future__ import annotations

import argparse
import json
import sys
from fnmatch import fnmatch
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
WORKFLOWS = ROOT / "workflows"
OUTPUT = WORKFLOWS / "CATALOG.md"

# (top-level path pattern under workflows/, owner component, release/verify entry)
OWNERSHIP: list[tuple[str, str, str]] = [
    ("quant-*.json", "quant-research", "`node scripts/hot-publish-quant-workflows.mjs` / `scripts/converge-*.sh`"),
    ("edge-relay/*", "feishu-relay", "`scripts/release edge workflows`；核验 `scripts/verify-edge-relay-workflows.sh`"),
    ("xhs-intel-edge.json", "xhs-intel", "`xhs-intel/scripts/publish-xhs-workflow-edge.sh --apply`"),
    ("paper-kb-automation.json", "platform（integration）", "手动 import 到本机 n8n"),
    ("runner-*.json", "platform（integration，诊断用）", "手动 import 到本机 n8n"),
    ("managed/*", "platform（integration）", "镜像；`scripts/export-n8n-workflow-source.sh --replace` 刷新"),
]


def _ownership(relative: str) -> tuple[str, str]:
    for pattern, owner, release in OWNERSHIP:
        if fnmatch(relative, pattern) or fnmatch(relative.split("/", 1)[0] + "/*", pattern):
            return owner, release
    return "未归属（给 config/components.json 或本表加规则）", "—"


def _load_workflows(path: Path) -> list[dict]:
    value = json.loads(path.read_text(encoding="utf-8"))
    return value if isinstance(value, list) else [value]


def _trigger_text(workflow: dict) -> str:
    parts: list[str] = []
    for node in workflow.get("nodes") or []:
        node_type = str(node.get("type") or "")
        parameters = node.get("parameters") or {}
        suffix = "（节点禁用）" if node.get("disabled") else ""
        if node_type.endswith("scheduleTrigger"):
            for item in (parameters.get("rule") or {}).get("interval") or [{}]:
                if item.get("field") == "cronExpression":
                    parts.append(f"cron `{item.get('expression', '?')}`{suffix}")
                else:
                    detail = json.dumps(item, ensure_ascii=False) if item else "every minute"
                    parts.append(f"interval {detail}{suffix}")
        elif node_type.endswith(".cron"):
            for item in (parameters.get("triggerTimes") or {}).get("item") or []:
                parts.append(f"cron {json.dumps(item, ensure_ascii=False)}{suffix}")
        elif node_type.endswith(".webhook"):
            method = parameters.get("httpMethod", "GET")
            parts.append(f"webhook {method} `/{parameters.get('path', '')}`{suffix}")
        elif node_type.endswith("errorTrigger"):
            parts.append(f"error trigger{suffix}")
        elif node_type.endswith("manualTrigger"):
            parts.append(f"manual{suffix}")
        elif node_type.endswith("executeWorkflowTrigger"):
            parts.append(f"sub-workflow{suffix}")
    return "；".join(parts) or "—"


def _active_text(workflow: dict) -> str:
    active = workflow.get("active")
    if active is None:
        return "—"
    return "✅" if active else "停用"


def _row(workflow: dict, relative: str, extra: str = "") -> str:
    owner, release = _ownership(relative)
    name = str(workflow.get("name") or "").replace("|", "/")
    cells = [
        f"`{workflow.get('id', '?')}`",
        name,
        _active_text(workflow),
        _trigger_text(workflow),
        owner,
        f"`workflows/{relative}`" + (f"<br>{extra}" if extra else ""),
        release,
    ]
    return "| " + " | ".join(cells) + " |"


HEADER = ["| id | 名称 | active | 触发 | 归属组件 | 源文件 | 发布 / 维护 |",
          "| --- | --- | --- | --- | --- | --- | --- |"]


def render() -> str:
    authored: dict[str, tuple[dict, str]] = {}
    authored_paths = sorted(p for p in WORKFLOWS.glob("*.json") if p.name != "xhs-intel-edge.json")
    for path in authored_paths:
        for workflow in _load_workflows(path):
            authored[str(workflow.get("id"))] = (workflow, path.name)

    out = [
        "# Workflows catalog",
        "",
        "> Generated by `python3 scripts/generate_workflows_catalog.py`; do not edit by hand.",
        "> 本机实例的运行时权威是 n8n 的 Postgres；`workflows/managed/` 是它的无凭据导出镜像，",
        "> 顶层 authored JSON 是人工编写的源（两者通过 id 关联，见「authored 源」标注）。",
        "> 归属与发布单元遵循 `workflows/AGENTS.md` 与 `config/components.json`。",
        "",
    ]

    managed_dir = WORKFLOWS / "managed" / "workflows"
    matched_authored: set[str] = set()
    rows = []
    for path in sorted(managed_dir.glob("*.json")):
        workflow = _load_workflows(path)[0]
        workflow_id = str(workflow.get("id"))
        extra = ""
        if workflow_id in authored:
            matched_authored.add(workflow_id)
            extra = f"authored 源：`workflows/{authored[workflow_id][1]}`"
            owner, release = _ownership(authored[workflow_id][1])
            row_workflow = workflow
            name = str(row_workflow.get("name") or "").replace("|", "/")
            rows.append("| " + " | ".join([
                f"`{workflow_id}`", name, _active_text(row_workflow), _trigger_text(row_workflow),
                owner, f"`workflows/managed/workflows/{path.name}`<br>{extra}", release,
            ]) + " |")
            continue
        rows.append(_row(workflow, f"managed/workflows/{path.name}"))
    out += [f"## 本机 n8n（workstation，compose `n8n`，127.0.0.1:5678）— {len(rows)} 个", "", *HEADER, *rows, ""]

    rows = []
    edge_dir = WORKFLOWS / "edge-relay" / "workflows"
    for path in sorted(edge_dir.glob("*.json")):
        workflow = _load_workflows(path)[0]
        rows.append(_row(workflow, f"edge-relay/workflows/{path.name}"))
    for workflow in _load_workflows(WORKFLOWS / "xhs-intel-edge.json"):
        rows.append(_row(workflow, "xhs-intel-edge.json"))
    out += [f"## 边缘 n8n（47edge，容器 `feishu-relay-edge-n8n`）— {len(rows)} 个", "", *HEADER, *rows, ""]

    leftovers = [(workflow, filename) for wid, (workflow, filename) in sorted(authored.items())
                 if wid not in matched_authored]
    if leftovers:
        rows = [_row(workflow, filename) for workflow, filename in leftovers]
        out += [f"## 仅 authored、当前不在任一实例镜像中 — {len(rows)} 个", "",
                "> 这些源文件没有对应的运行时镜像行：要么尚未导入，要么实例侧已删除。",
                "> 用 `bash scripts/workflow-status.sh` 核对真实运行态。", "", *HEADER, *rows, ""]

    return "\n".join(out)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    text = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != text:
            print("workflows/CATALOG.md is stale; run python3 scripts/generate_workflows_catalog.py", file=sys.stderr)
            return 1
        print("workflows catalog is current")
        return 0
    OUTPUT.write_text(text, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
