#!/usr/bin/env python3
"""Generate a small, deterministic map for humans and maintenance agents.

The index intentionally lists ownership boundaries rather than source contents.
It is checked in so an agent can orient itself without scanning the whole tree;
``--check`` makes documentation drift a CI failure.
"""

from __future__ import annotations

import argparse
import ast
from collections import Counter
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parents[1]
APP = ROOT / "quant-service" / "app"
ROUTERS = APP / "routers"
MIGRATIONS = ROOT / "quant-service" / "migrations" / "versions"
FRONTEND = ROOT / "frontend" / "src"
OUTPUT = ROOT / "docs" / "ARCHITECTURE_INDEX.md"


def _python_files(path: Path) -> list[Path]:
    return sorted(item for item in path.rglob("*.py") if "__pycache__" not in item.parts)


def _functions(path: Path) -> int:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    return sum(isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)) for node in tree.body)


def _prefix(path: Path) -> str:
    stem = path.stem
    for marker in ("_repository", "_read_model", "_service", "_scheduler", "_runtime", "_actions", "_rules", "_research"):
        if marker in stem:
            stem = stem.split(marker, 1)[0]
    return stem.split("_", 1)[0]


def render() -> str:
    app_files = _python_files(APP)
    router_files = _python_files(ROUTERS)
    frontend_files = sorted(item.relative_to(ROOT).as_posix() for item in FRONTEND.rglob("*") if item.is_file() and "node_modules" not in item.parts)
    prefixes = Counter(_prefix(path) for path in app_files if path.parent == APP)
    main = APP / "main.py"
    top_functions = _functions(main)
    rows = "\n".join(f"| `{name}` | {count} |" for name, count in sorted(prefixes.items(), key=lambda item: (-item[1], item[0]))[:18])
    router_rows = "\n".join(f"- `{path.relative_to(APP).as_posix()}`" for path in router_files)
    frontend_rows = "\n".join(f"- `{path}`" for path in frontend_files)
    return f"""# Generated Architecture Index

> Generated by `python3 scripts/generate_architecture_index.py`; do not edit manually.
> Run `python3 scripts/generate_architecture_index.py --check` in CI or before an Agent handoff.

## Composition and size

| Item | Current value |
|---|---:|
| Composition root | `quant-service/app/main.py` |
| `main.py` top-level functions | {top_functions} |
| Python modules under `app/` | {len(app_files)} |
| HTTP router modules | {len(router_files)} |
| Alembic migrations | {len(list(MIGRATIONS.glob('*.py')))} |
| Frontend source files | {len(frontend_files)} |

## Domain naming inventory

The counts below are a navigation aid, not a license to add more flat modules.
New behaviour should be owned by an existing domain package/owner.

| Domain prefix | Top-level modules |
|---|---:|
{rows}

## Router entrypoints

{router_rows}

## Frontend entrypoints

{frontend_rows}

## Maintenance route

1. Read `GET /api/v1/agent/context`.
2. Find the owning router, service, repository, migration and focused test.
3. Preserve the `raw -> canonical -> features -> signals -> outcomes` evidence boundary.
4. Run the relevant test, then the full verification sequence documented in `docs/ARCHITECTURE.md`.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the checked-in index is stale")
    args = parser.parse_args()
    rendered = render()
    if args.check:
        if not OUTPUT.is_file() or OUTPUT.read_text(encoding="utf-8") != rendered:
            print("architecture index is stale; run python3 scripts/generate_architecture_index.py")
            return 1
        print("architecture index is current")
        return 0
    OUTPUT.write_text(rendered)
    print(OUTPUT.relative_to(ROOT))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
