from pathlib import Path
import unittest


SCRIPT = Path(__file__).with_name("shared-peer") / "activate-peer-release.sh"
TUNNEL_SCRIPTS = (
    SCRIPT.with_name("start-shared-tunnels.ps1"),
    SCRIPT.with_name("start-shared-peer-batch-tunnel.ps1"),
    SCRIPT.with_name("verify-shared-runtime.ps1"),
)


class ActivatePeerReleaseTests(unittest.TestCase):
    def test_source_packager_is_present_and_checks_runtime_assets(self) -> None:
        packager = SCRIPT.with_name("package-peer-release.sh")
        source = packager.read_text(encoding="utf-8")
        self.assertIn("scripts/peer-session-guard.sh", source)
        self.assertIn("scripts/backfill-full-market-daily.sh", source)
        self.assertIn("OPERATIONS.md", source)
        self.assertIn("tar -czf", source)

    def test_release_validation_requires_two_lane_runtime_files(self) -> None:
        source = SCRIPT.read_text(encoding="utf-8")
        self.assertIn('compose.intraday-owner.yaml', source)
        self.assertIn('scripts/peer-session-guard.sh', source)
        self.assertIn('scripts/backfill-full-market-daily.sh', source)
        self.assertIn('OPERATIONS.md', source)
        self.assertIn('frontend', source)
        self.assertIn('workflows', source)
        self.assertIn('certs', source)
        self.assertIn("grep -q 'PEER_REQUIRE_OWNER_SEMANTICS'", source)
        self.assertIn("grep -q 'owner_semantics_required'", source)
        self.assertIn("owner_peer_contract.py", source)
        self.assertIn("api/v1/peer/contract", source)
        self.assertIn('ssh-tunnel-entrypoint.sh', source)
        self.assertIn("grep -q 'LOCAL_DB_BIND_PORT'", source)
        self.assertIn("5433:127.0.0.1:15433", source)
        self.assertIn('ensure-batch-tunnel.sh', source)
        self.assertIn('verify-owner-cutover.py', source)
        self.assertIn("grep -q 'no_security_definer_functions'", source)
        self.assertIn("grep -q 'no_role_memberships'", source)
        self.assertIn("grep -q 'no_quant_relation_dml'", source)
        self.assertIn("grep -q 'no_quant_sequence_writes'", source)
        self.assertIn('bootstrap-local-peer.ps1', source)
        self.assertIn("grep -q '\\[switch\\]\\$DryRun'", source)
        self.assertIn("REVOKE ALL PRIVILEGES ON ALL TABLES IN SCHEMA quant", source)
        self.assertIn("REVOKE ALL PRIVILEGES ON SCHEMA quant", source)
        self.assertIn("REVOKE ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA quant", source)
        self.assertIn("REVOKE ALL PRIVILEGES ON ALL PROCEDURES IN SCHEMA quant", source)
        self.assertIn("NOSUPERUSER NOCREATEDB NOCREATEROLE NOREPLICATION NOBYPASSRLS NOINHERIT", source)
        self.assertIn("CREATE ROLE \\$PeerRole LOGIN NOINHERIT", source)
        self.assertIn("ALTER ROLE \\$PeerRole LOGIN NOINHERIT", source)
        self.assertIn("statement_timeout = '15min'", source)
        self.assertIn("idle_in_transaction_session_timeout = '5min'", source)
        self.assertIn("REVOKE %I FROM %I", source)
        self.assertIn("WritableQuantRelationCount", source)
        self.assertIn("WritableQuantSequenceCount", source)
        self.assertIn("REASSIGN OWNED BY $PeerRole TO $($runtime.PGADMINUSER)", source)
        self.assertIn("ALTER DATABASE $PeerN8nDatabase OWNER TO $PeerRole", source)
        self.assertIn("unexpected shared objects", source)
        self.assertIn("pg_get_userbyid(datdba)", source)
        self.assertIn("ALTER DATABASE $($runtime.PGDATABASE) OWNER TO $($runtime.PGADMINUSER)", source)
        self.assertIn("pg_get_userbyid(nspowner)", source)
        self.assertIn("ALTER SCHEMA quant OWNER TO $($runtime.PGADMINUSER)", source)
        self.assertIn("has_schema_privilege('\\$PeerRole','quant','CREATE')", source)
        self.assertIn("rolinherit FROM pg_roles", source)
        self.assertIn("datdba", source)
        self.assertIn("nspowner", source)
        self.assertIn("c.relowner", source)
        self.assertIn('quant-service/app/owner_storage.py', source)
        self.assertIn("OWNER_RUNTIME_REQUIRED_COLUMNS", source)
        self.assertIn("canonical_bars_daily", source)
        self.assertIn("daily_adjustment_factors", source)
        self.assertIn("persisted_factor_semantics_sql", source)
        self.assertIn("raw->>'factor_semantics'", source)
        self.assertIn('quant-service/app/event_research.py', source)
        self.assertIn("persisted_adj_factor", source)
        self.assertIn("daily_adjustment_factors", source)
        self.assertIn('owner_factor_repository.py', source)
        self.assertIn("owner_persisted_adjustment_factor", source)
        self.assertIn("full_market_daily_controls_sync.py", source)
        self.assertIn("core_daily_control_sync.py", source)
        self.assertIn("stock_study_service.py", source)
        self.assertIn('quant-service/app/main.py', source)
        self.assertIn('read_persisted_factor_window', source)
        self.assertIn('post_close_strategy_service.py', source)
        self.assertIn('quant-service/app/instrument_registry.py', source)
        self.assertIn('quant-service/app/instrument_lock_retry.py', source)
        self.assertIn("ORDER BY symbol", source)
        self.assertIn('quant-service/app/replay_readiness_coverage.py', source)
        self.assertIn("grep -q 'complete_adjusted'", source)
        self.assertIn("EXPECTED_REPLAY_COVERAGE_DEFINITION", source)
        self.assertIn('set_env_if_placeholder PEER_APP_RELEASE', source)
        self.assertIn('set_env_if_placeholder PEER_EXPECTED_RELEASE', source)
        self.assertIn('app_release=', source)
        self.assertIn('APP_BUILD_CREATED_AT', source)

    def test_scheduler_release_carries_explicit_owner_cutover_policy(self) -> None:
        compose = (SCRIPT.parents[2] / "deploy" / "shared-peer" / "compose.intraday-owner.yaml").read_text(encoding="utf-8")
        self.assertIn("dockerfile: quant-service/Dockerfile.peer", compose)
        self.assertIn("PEER_QUANT_IMAGE", compose)
        self.assertIn("PEER_REQUIRE_OWNER_CUTOVER", compose)
        self.assertIn("${PEER_REQUIRE_OWNER_CUTOVER:-auto}", compose)
        self.assertIn("PEER_REQUIRE_OWNER_SEMANTICS", compose)
        base = (SCRIPT.parents[2] / "deploy" / "shared-peer" / "compose.yaml").read_text(encoding="utf-8")
        self.assertIn("image: ${PEER_QUANT_IMAGE:-trading-hareness-peer-quant-research:latest}", base)
        self.assertIn("PEER_REQUIRE_OWNER_SEMANTICS", base)

    def test_tunnel_scripts_accept_direct_host_port_user_and_key(self) -> None:
        for path in TUNNEL_SCRIPTS:
            source = path.read_text(encoding="utf-8")
            self.assertIn("SshHost", source)
            self.assertIn("SshPort", source)
            self.assertIn("SshUser", source)
            self.assertIn("SshKeyPath", source)
            self.assertIn("KnownHostsPath", source)
            self.assertIn("IdentitiesOnly=yes", source)
            self.assertIn("StrictHostKeyChecking=yes", source)
            self.assertIn("PEER_SSH_HOST", source)


if __name__ == "__main__":
    unittest.main()
