import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

const source = readFileSync(fileURLToPath(new URL('./deploy-xhs-intel-edge.sh', import.meta.url)), 'utf8');
const workflow = JSON.parse(readFileSync(fileURLToPath(new URL('../../workflows/xhs-intel-edge.json', import.meta.url)), 'utf8'))[0];

assert.match(source, /scp -q -i "\$edge_key"/);
assert.doesNotMatch(source, /scp -q "\$\{ssh_command\[@\]\}"/);
assert.match(source, /XHS_COOKIE_SOURCE/);
assert.doesNotMatch(source, /\$source_root\/\.env/);
assert.match(source, /config\/secrets\/\.env\.local/);
assert.match(source, /a1/);
assert.match(source, /web_session/);
assert.match(source, /sync-secrets\.sh" edge/);
assert.match(source, /XHS_FORCE_BUILD/);
assert.match(source, /docker image inspect feishu-relay-edge-xhs:local/);
assert.match(source, /xhs_git_sha/);
assert.match(source, /xhs_source_digest/);
assert.match(source, /root \/ 'dashboard'/);
assert.match(source, /not path\.name\.startswith\('test_'\)/);
assert.match(source, /== test_\*\.py/);
assert.match(source, /xhs-intel\/dashboard/);
assert.match(source, /127\.0\.0\.1:18790\/xhs\//);
assert.match(source, /update_env "\$runtime_env" XHS_HOTFIX_ENABLED "false"/);
assert.match(source, /\/proc\/1\/cmdline/);
assert.match(source, /\/app\/hotfix\/current\//);
assert.match(source, /\/app\/edge_api\.py/);
assert.match(source, /XHS_SOURCE_TREE_SHA256/);
assert.match(source, /xhs-manifest\.json/);
assert.match(source, /build_required=false/);
assert.match(source, /docker compose --env-file "\$runtime_env" --env-file "\$secrets_env" build[\s\S]*--build-arg BASE_IMAGE="\$xhs_base_image"[\s\S]*xhs-collector/);
assert.match(source, /N8N_RUNNERS_AUTH_TOKEN/);
assert.match(source, /n8n-runners/);
assert.doesNotMatch(source, /UPDATE execution_entity|status='crashed'/);
assert.equal(workflow.settings.saveDataSuccessExecution, 'all');
assert.equal(workflow.settings.saveDataErrorExecution, 'all');
assert.match(source, /XHS workflow unchanged; skipping import and restart/);
assert.match(source, /stop n8n/);
assert.match(source, /before\.json/);
assert.match(source, /import:workflow --input=\/xhs-deploy\/candidate\.json/);
assert.doesNotMatch(source, /\.xhs-credentials/);
assert.doesNotMatch(source, /update_env "\$secrets_env"/);
assert.match(source, /XHS workflow was not activated after n8n restart/);

console.log('XHS deployment validates the private Cookie and provisions an external n8n task runner');
